import { zodResolver } from '@hookform/resolvers/zod';
import CardV2 from 'app/components/CardV2/CardV2';
import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT } from 'app/constants/common';
import { PATH } from 'app/constants/path';
import useEmployee from 'app/hooks/use-employee';
import useIncomingInvoice from 'app/hooks/use-incoming-invoice';
import usePaymentRequest from 'app/hooks/use-payment-request';
import { useModalsRefundRequest } from 'app/hooks/use-refund-request';
import { FORM } from 'app/shared/model/enumerations/form.model';
import {
  PAYMENT_REQUEST_STATUS,
  PAYMENT_REQUEST_TYPE,
} from 'app/shared/model/enumerations/payment-request';
import {
  RefundRequestSchema,
  refundRequestSchema,
} from 'app/validation/request-payment.validation';
import dayjs from 'dayjs';
import { useEffect } from 'react';
import { FormProvider, SubmitHandler, useForm } from 'react-hook-form';
import { DateObject } from 'react-multi-date-picker';
import { useNavigate, useParams } from 'react-router';
import { ButtonGroupHeader } from '../components/ButtonGroupHeader';
import RefundRequestApproveModals from './refund-request-approve-modals';
import RefundRequestApproveSuccessModals from './refund-request-approve-success-modals';
import RefundRequestCancelModals from './refund-request-cancel-modals';
import RefundRequestCancelSuccessModals from './refund-request-cancel-success-modals';
import RefundRequestCreateSuccessModals from './refund-request-create-success-modal';
import RefundRequestForm from './refund-request-form';
import RefundRequestUpdateSuccessModals from './refund-request-update-success-modals';
import AuthGuard from 'app/components/guards/auth-guard';

const {
  usePostPaymentRequest,
  usePatchPaymentRequest,
  useGetPaymentRequestAutoGeneratedCode,
  useGetPaymentRequestById,
} = usePaymentRequest;
const { useNextIncomingInvoiceNumber } = useIncomingInvoice;
const { useGetEmployeesQuery } = useEmployee;

function VoucherAdvanceRepaymentCreateModals() {
  const navigate = useNavigate();
  const { id } = useParams();

  const account = useAppSelector(state => state.authentication.account);

  const [
    { openApprovalSign, toggleApprovalSign },
    { openApprovalSignSuccess, toggleApprovalSignSuccess },
    { openReject, toggleReject },
    { openRejectSuccess, toggleRejectSuccess },
    { openCancel, toggleCancel },
    { openCancelSuccess, toggleCancelSuccess },
    { openCreateSuccess, toggleCreateSuccess },
    { openUpdateSuccess, toggleUpdateSuccess },
  ] = useModalsRefundRequest();

  let defaultPaymentDetail = {
    new: true,
    invoiceId: '',
    incomingInvoice: {
      invoiceNo: '',
      invoiceDate: new Date().toISOString(),
      totalAmount: '0',
      note: '',
    },
  };

  const methods = useForm<RefundRequestSchema>({
    defaultValues: {
      status: PAYMENT_REQUEST_STATUS.NEW,
      attachments: [],
      requestApprovals: [],
      paymentDetails: [{ ...defaultPaymentDetail }],
      paymentDate: new DateObject(),
      createdDate: new DateObject(),
      createdByName: `${account?.lastName} ${account?.firstName}`,
    },
    resolver: zodResolver(refundRequestSchema),
  });

  const { handleSubmit, setValue, reset, watch, formState } = methods;

  const statusWatch = watch('status');
  const createdByWatch = watch('createdBy');
  const paymentDetailsWatch = watch('paymentDetails');

  const { mutateAsync: create } = usePostPaymentRequest(toggleCreateSuccess);
  const { mutateAsync: update } = usePatchPaymentRequest(
    id,
    toggleUpdateSuccess,
  );
  const { data: employeeProfiles } = useGetEmployeesQuery();

  const { data: detail } = useGetPaymentRequestById(id);
  const { data: nextCode } = useGetPaymentRequestAutoGeneratedCode(
    PAYMENT_REQUEST_TYPE.REIMBURSEMENT,
  );
  const { data: nextInvoiceCode } = useNextIncomingInvoiceNumber();

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode)
        setValue('code', `HU${suffix}/${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  const onSubmit: SubmitHandler<RefundRequestSchema> = values => {
    const totalAmount = values.reimbursements.reduce(
      (acc, obj) => acc + (Number(obj?.advancement?.totalAmount) ?? 0),
      0,
    );

    const paidAmount = values.paymentDetails
      ?.filter(x => x.incomingInvoice?.invoiceNo)
      .reduce(
        (acc, obj) => acc + (Number(obj?.incomingInvoice?.totalAmount) ?? 0),
        0,
      );
    const paymentVoucherAmount = values.reimbursements.reduce(
      (acc, obj) => acc + (Number(obj?.advancement?.paymentVoucherAmount) ?? 0),
      0,
    );
    if (!id) {
      create({
        code: values.code,
        order: undefined,
        type: PAYMENT_REQUEST_TYPE.REIMBURSEMENT,
        attachments: values.attachments.map(x => ({
          fileId: x.fileId,
          fileName: x.fileName,
          createdAt: new Date(x.createdAt),
        })),
        totalAmount: totalAmount ?? 0,
        paidAmount: paidAmount ?? 0,
        remainingAmount: paymentVoucherAmount - paidAmount,
        paymentDate: values.paymentDate.toDate(),
        note: values.note,
        content: values?.content,
        status: PAYMENT_REQUEST_STATUS.NEW,
        paymentVoucher: undefined, // Phiếu chi
        paymentVoucherAmount: paymentVoucherAmount ?? 0, // Tổng tiền chi
        remainingBalance: Math.abs(Number(values?.remainingBalance)), // Số tiền tạm ứng còn lại
        overSpent: Math.abs(Number(values?.overSpent)), // Tổng số tiền tạm ứng vượt quá
        employeeId: values.employeeId,
        supplierId: values.supplierId,
        requestApprovals: values.requestApprovals
          ?.filter(x => x.employeeId)
          ?.map(x => ({
            index: x.index,
            employeeId: x.employeeId,
          })),
        paymentDetails: values.paymentDetails
          ?.filter(
            x =>
              x.incomingInvoice?.totalAmount !== '0' &&
              x.incomingInvoice?.totalAmount !== '',
          )
          .map(x => ({
            invoiceId: x.invoiceId,
            incomingInvoice: {
              invoiceNo: x.incomingInvoice?.invoiceNo,
              invoiceDate: new Date(),
              content: x.incomingInvoice?.content,
              totalAmount: Number(x.incomingInvoice?.totalAmount),
              series: x.incomingInvoice?.series,
              note: x.incomingInvoice?.note,
              documentId: x.incomingInvoice?.documentId,
              grandTotal: Number(x.incomingInvoice?.totalAmount),
            },
          })),
        reimbursementDTOS: values?.reimbursements?.map(x => ({
          advanceId: x.advanceId,
        })),
      }).then(() => reset());
      return;
    } else {
      update({
        id: id ?? '',
        code: values?.code,
        type: PAYMENT_REQUEST_TYPE.REIMBURSEMENT,
        attachments: values.attachments.map(x => ({
          fileId: x.fileId,
          fileName: x.fileName,
          createdAt: new Date(x.createdAt),
        })),
        totalAmount: totalAmount ?? 0,
        paidAmount: paidAmount ?? 0,
        remainingAmount: totalAmount - paidAmount,
        paymentDate: values.paymentDate.toDate(),
        note: values.note,
        content: values?.content,
        status: PAYMENT_REQUEST_STATUS.NEW,
        paymentVoucher: undefined, // Phiếu chi
        paymentVoucherAmount: paymentVoucherAmount ?? 0, // Tổng tiền chi
        remainingBalance: Math.abs(Number(values?.remainingBalance)), // Số tiền tạm ứng còn lại
        overSpent: Math.abs(Number(values?.overSpent)), // Tổng số tiền tạm ứng vượt quá
        employeeId: values.employeeId,
        requestApprovals: values.requestApprovals
          ?.filter(x => x.employeeId)
          ?.map(x => ({
            index: x.index,
            employeeId: x.employeeId,
          })),
        paymentDetails: values.paymentDetails
          ?.filter(
            x =>
              x.incomingInvoice?.invoiceNo &&
              x.incomingInvoice?.totalAmount !== '0' &&
              x.incomingInvoice?.totalAmount !== '',
          )
          .map(x => ({
            id: x.id,
            invoiceId: x.invoiceId,
            incomingInvoice: {
              invoiceNo: x.incomingInvoice?.invoiceNo,
              invoiceDate: new Date(),
              content: x.incomingInvoice?.content,
              totalAmount: Number(x.incomingInvoice?.totalAmount),
              series: x.incomingInvoice?.series,
              note: x.incomingInvoice?.note,
              documentId: x.incomingInvoice?.documentId,
              grandTotal: Number(x.incomingInvoice?.totalAmount),
            },
          })),
        reimbursementDTOS: values?.reimbursements?.map(x => ({
          id: x.id,
          advanceId: x.advanceId,
        })),
      });
    }
  };

  const loadDefaultPaymentDetail = () => {
    if (nextInvoiceCode?.nextAndIncrement) {
      if (id) {
        defaultPaymentDetail = {
          ...defaultPaymentDetail,
          incomingInvoice: {
            ...defaultPaymentDetail.incomingInvoice,
            invoiceNo: nextInvoiceCode?.nextAndIncrement,
          },
        };
        if (detail) {
          const existPaymentDetail = detail?.paymentDetails?.map(x => ({
            ...x,
            id: x.id,
            incomingInvoice: {
              ...x.incomingInvoice,
              totalAmount: (x?.incomingInvoice?.grandTotal ?? 0)?.toString(),
              // totalAmount: (x?.incomingInvoice?.totalAmount ?? 0)?.toString(),
              invoiceDate: new Date(
                x.incomingInvoice.invoiceDate,
              )?.toISOString(),
            },
          }));
          setValue('paymentDetails', [
            ...existPaymentDetail,
            defaultPaymentDetail,
          ]);
        }
      } else {
        const defaultItem = paymentDetailsWatch.findIndex(
          x =>
            x.incomingInvoice.totalAmount === '0' &&
            x.incomingInvoice.invoiceNo === '',
        );
        if (defaultItem > -1) {
          const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
          setValue(
            `paymentDetails.${defaultItem}.incomingInvoice.invoiceNo`,
            `HDNK${suffix}/${nextInvoiceCode?.nextAndIncrement}`,
          );
        }
      }
    }
  };

  useEffect(() => {
    if (detail) {
      setValue('code', detail?.code);
      setValue('paymentDate', new DateObject(detail?.paymentDate));
      setValue('supplierId', `${detail?.suppliers?.id}`);
      setValue('supplierCodeName', `${detail?.suppliers?.name}`);
      setValue('content', detail?.content);
      setValue('status', detail?.status);
      setValue('employeeId', detail?.employeeId);

      const empSelected = employeeProfiles?.data?.find(
        x => x.id === detail?.employeeId,
      );
      const empWorkspace = empSelected
        ? `${empSelected.workspace.normalizedName} - ${empSelected.workspace?.name}`
        : '';
      setValue('workspaceName', empWorkspace);

      setValue('requestApprovals', detail?.requestApprovals);
      setValue('remainingBalance', `${detail?.remainingBalance ?? 0}`);
      setValue('overSpent', `${detail?.overSpent ?? 0}`);
      const existPaymentDetail = detail?.paymentDetails?.map(x => ({
        ...x,
        id: x.id,
        incomingInvoice: {
          ...x.incomingInvoice,
          totalAmount: `${x?.incomingInvoice?.grandTotal ?? 0}`,
          // totalAmount: `${x?.incomingInvoice?.totalAmount ?? 0}`,
          invoiceDate: new Date(x.incomingInvoice.invoiceDate)?.toISOString(),
        },
      }));
      setValue('paymentDetails', [...existPaymentDetail, defaultPaymentDetail]);

      setValue(
        'attachments',
        detail?.attachments?.map(x => ({
          ...x,
          createdAt: new Date(x.createdAt),
        })),
      );
      setValue(
        'reimbursements',
        detail?.reimbursementDTOS?.map(x => ({
          id: x.id,
          advanceId: x.advanceId,
          advancement: { ...x.advancement },
        })),
      );

      setValue('createdDate', new DateObject(detail?.createdDate));

      const createdByName = [
        detail?.createdByEmployee?.employeeCode,
        detail?.createdByEmployee?.fullName,
      ].join(' - ');
      setValue('createdByName', createdByName);
      setValue('createdBy', detail?.createdBy);
    }

    loadDefaultPaymentDetail();
  }, [detail, employeeProfiles, nextInvoiceCode]);

  return (
    <>
      <FormProvider {...methods}>
        <Form id={FORM.CREATE_HTU} onSubmit={handleSubmit(onSubmit)}>
          <CardV2
            header={
              <Flex justify="space-between" align="center">
                <Typography level={4}>DNHU</Typography>
                <AuthGuard permissionKey={!!id ? 'REQUEST_PAYMENT.EDIT' : 'REQUEST_PAYMENT.CREATE'}>
                  <ButtonGroupHeader
                    status={statusWatch}
                    createdBy={createdByWatch}
                    toggleCancel={toggleCancel}
                    toggleSendApprove={toggleApprovalSign}
                    disableSendApproved={detail?.requestApprovals?.length === 0}
                    type={PAYMENT_REQUEST_TYPE.REIMBURSEMENT}
                  />
                </AuthGuard>
              </Flex>
            }
          >
            <RefundRequestForm />
          </CardV2>
        </Form>
      </FormProvider>

      <RefundRequestCreateSuccessModals
        isOpen={openCreateSuccess}
        toggle={() => {
          toggleCreateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RefundRequestUpdateSuccessModals
        isOpen={openUpdateSuccess}
        toggle={() => {
          toggleUpdateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RefundRequestApproveModals
        isOpen={openApprovalSign}
        selectedRecord={id}
        toggle={toggleApprovalSign}
        toggleSuccess={toggleApprovalSignSuccess}
      />

      <RefundRequestApproveSuccessModals
        isOpen={openApprovalSignSuccess}
        toggle={() => {
          toggleApprovalSignSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RefundRequestCancelModals
        isOpen={openCancel}
        toggle={toggleCancel}
        toggleSuccess={toggleCancelSuccess}
        selectedRecord={id}
      />

      <RefundRequestCancelSuccessModals
        isOpen={openCancelSuccess}
        toggle={() => {
          toggleCancelSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />
    </>
  );
}

export default VoucherAdvanceRepaymentCreateModals;
