configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGEwMzM2OGMxMDk5NDE5OTVkMjY0N2M5Y2Q2ZDBlODRhODgxNmY1NmJmZDZmYTNlZDY2ZTcyYzM2YTQ2Njg4YzI2ZDhjMDQ4NGVmZjNmNjk4ZjdhMmQ5ZTM4NDkxYWZiYzEwOTkyOWIxYmVhMzUxMGMwMjZkMTYwM2M3NWQ4ZTI=
