import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import FormSelect from 'app/components/form/form-select';
import FormDatePickerV2 from 'app/components/formV2/form-date/form-date-picker';
import FormInputV2 from 'app/components/formV2/form-input/form-input';
import Input from 'app/components/input/input';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT, DEFAULT_PAGE_SIZE_NAX } from 'app/constants/common';
import useEmployee from 'app/hooks/use-employee';
import {
  useGetInventoriesAutoGeneratedCode,
  useInventoriesTypes,
  usePatchInventories,
  usePostInventories,
} from 'app/hooks/use-inventories';
import useItems from 'app/hooks/use-items';
import useProductionCommand from 'app/hooks/use-production-command';
import useSupplier from 'app/hooks/use-supplier';
import useWarehouse from 'app/hooks/use-warehouse';
import { FORM } from 'app/shared/model/enumerations/form.model';
import { InventoriesWarehouse } from 'app/shared/model/enumerations/warehouse.model';
import {
  IInventoriesStorage,
  INVENTORIES_STATUS,
} from 'app/shared/model/inventories-storage.model';
import { InventoriesSchema } from 'app/validation/inventories.validation';
import dayjs from 'dayjs';
import { useContext, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import { useParams } from 'react-router';
import { useSearchParams } from 'react-router-dom';
import { Col, FormGroup, Label, Row } from 'reactstrap';
import { InventoriesStorageContext } from '../inventories-storage-provider';
import InventoriesAttachments from './InventoriesAttachments';
import { InventoriesConnect } from './InventoriesConnects';
import { InventoriesItemsTable } from './InventoriesItemsTable';
import InventoriesPersonSign from './InventoriesPersonSign';

const { useGetProductionCommandsWithProcessById } = useProductionCommand;
const { useGetWarehouses } = useWarehouse;
const { useGetSuppliers } = useSupplier;
const { useGetItemsQuery } = useItems;

interface IInventoriesFormProps {
  type: 'create' | 'update';
  data?: IInventoriesStorage;
}

const { useGetEmployeesQuery } = useEmployee;

const InventoriesForm = ({ type, data }: IInventoriesFormProps) => {
  const { id } = useParams();
  const [searchParams] = useSearchParams();

  const account = useAppSelector(state => state.authentication.account);

  const { toggleCreateSuccess, toggleUpdateSuccess } = useContext(
    InventoriesStorageContext,
  );

  const { data: warehouses } = useGetWarehouses({
    size: DEFAULT_PAGE_SIZE_NAX,
  });
  const { data: inventoriesTypes } = useInventoriesTypes({
    size: DEFAULT_PAGE_SIZE_NAX,
  });
  const { data: suppliers } = useGetSuppliers();

  const { mutate: createInventories } = usePostInventories();
  const { mutate: updateInventories } = usePatchInventories(id);
  const { data: nextCode } = useGetInventoriesAutoGeneratedCode();
  const { data: employees, isLoading } = useGetEmployeesQuery({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const {
    control,
    handleSubmit,
    setValue,
    watch,
    reset,
    formState,
    getValues,
  } = useFormContext<InventoriesSchema>();

  const productionId = watch('productionId');

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode) setValue('code', `${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  useEffect(() => {
    if (employees?.data?.length && account?.id && !id) {
      const selected = employees?.data?.find(x => `${x.id}` === account?.id);
      if (selected)
        setValue(
          'createdByName',
          `${selected?.code} - ${selected?.lastName} ${selected?.firstName}`,
        );
    }
  }, [employees]);

  const { trigger, data: productionProcessDetail } =
    useGetProductionCommandsWithProcessById(productionId);

  useEffect(() => {
    if (watch('productionId')) trigger();
  }, [watch('productionId')]);

  const { data: items } = useGetItemsQuery({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  useEffect(() => {
    const item: any = {
      id: productionProcessDetail?.data.itemId,
      quantity: productionProcessDetail?.data?.productionQuantity ?? 0,
    };
    const itemData = items?.data?.find(a => a.id === item.id);

    if (!id) {
      if (itemData) {
        setValue('inventoriesDetails.0.itemId', itemData?.id);
        setValue('inventoriesDetails.0.uomId', itemData?.uomId);
        setValue('inventoriesDetails.0.quantity', item?.quantity);
        setValue('inventoriesDetails.0.price', itemData?.price);
        //  setValue('inventoriesDetails.0.totalPrice', Number(item?.quantity ?? 0) * Number(itemData?.price ?? 0))
      }
    }
  }, [productionProcessDetail]);

  const onSubmit = (values: InventoriesSchema) => {
    const submitValues = {
      ...values,
      dateCreate: values.dateCreate.format(DATE_FORMAT.YEAR_DATE),
      createdAt: values.createdAt.format(DATE_FORMAT.YEAR_DATE),
      inventoriesDetails: values.inventoriesDetails.map(detail => ({
        ...detail,
        uomId: detail.uomId,
        price: Number(detail.price),
        quantity: Number(detail.quantity),
        totalPrice: Number(detail.totalPrice),
        code: detail.code,
      })),
      file: values.file?.map(f => ({
        fileId: f.fileId,
        fileName: f.fileName,
        createdAt: f.createdAt,
      })),
      attribute: {
        shipper: values.shipper,
        shipperPhone: values.shipperPhone,
      },
      totalAmount: values?.inventoriesDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.price || 0) * Number(item?.quantity || 0);
        return acc;
      }, 0),
      totalQuantity: values?.inventoriesDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.quantity);
        return acc;
      }, 0),
      requestApprovals: values.isNoReview
        ? []
        : values.requestApprovals
            ?.filter(x => x.employeeId)
            ?.map(x => ({
              index: x.index,
              employeeId: x.employeeId,
            })),
      status: INVENTORIES_STATUS.NEW,
      warehouseGroupType:
        searchParams.get('warehouse') ??
        InventoriesWarehouse?.WAREHOUSE_DEPRECIATION_IMPORT,
      isReview: !values.isNoReview,
      productionId: values?.productionId,
    };

    if (type === 'update') {
      updateInventories(submitValues, {
        onSuccess: () => {
          toggleUpdateSuccess();
          reset();
        },
      });
      return;
    }

    createInventories(submitValues, {
      onSuccess: () => {
        toggleCreateSuccess();
        reset();
      },
    });
  };

  const isInvoice = watch('isInvoice');

  const disabled =
    watch('status') === (INVENTORIES_STATUS.WAITING_APPROVED as string) ||
    watch('status') === (INVENTORIES_STATUS.CANCELLED as string) ||
    watch('status') === (INVENTORIES_STATUS.APPROVED as string) ||
    watch('status') === (INVENTORIES_STATUS.COMPLETED as string);

  return (
    <Form id={FORM.INVENTORIES} onSubmit={handleSubmit(onSubmit)}>
      <Flex direction="column" gap={20}>
        <Typography level={5}>Thông tin chung</Typography>
        <Row>
          <Col md={3}>
            <FormInputV2
              control={control}
              name="code"
              label="Mã phiếu"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="incomingWarehouseId"
              label="Kho"
              options={warehouses?.data?.map(w => ({
                label: `${w?.code} - ${w?.name}`,
                value: w?.id,
              }))}
              placeholder="Chọn"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="inventoriesTypeId"
              label="Loại nhập"
              options={inventoriesTypes?.data?.map(it => ({
                label: `${it?.code} - ${it?.name}`,
                value: it?.id,
              }))}
              placeholder="Chọn loại nhập"
              disabled={type === 'update'}
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="dateCreate"
              label="Ngày nhập kho"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="employeeId"
              label="Nhân viên"
              placeholder="Mã - Tên nhân viên"
              options={employees?.data?.map(e => ({
                label: `${e.code} - ${e.employeeProfile?.fullName}`,
                value: e?.id,
              }))}
              isLoading={isLoading}
              onChanges={e => {
                const selected = employees?.data?.find(x => `${x.id}` === e);
                if (selected)
                  setValue(
                    'workspaceName',
                    `${selected?.workspace?.normalizedName} - ${selected?.workspace?.name}`,
                  );
              }}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="workspaceName"
              label="Bộ phận"
              disabled
            />
          </Col>

          <Col md={6}>
            <FormGroup>
              <Flex direction="column" justify="space-between">
                <div style={{ height: '40px' }} />
                <Flex gap={8}>
                  <Input
                    id="isInvoice"
                    placeholder="Chọn"
                    type="checkbox"
                    checked={isInvoice}
                    onChange={e => {
                      e.target.checked
                        ? setValue('isInvoice', true)
                        : setValue('isInvoice', false);
                    }}
                    disabled={disabled}
                  />
                  <Label for="isInvoice">Đã có hoá đơn</Label>
                </Flex>
              </Flex>
            </FormGroup>
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="createdByName"
              label="Người tạo"
              placeholder="Mã - Tên nhân viên"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              name="createdAt"
              label="Ngày lập phiếu"
              disabled
            />
          </Col>

          <Col md={12}>
            <FormInputV2
              control={control}
              name="note"
              label="Diễn giải"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>
        </Row>

        <Typography level={5}>NCC</Typography>
        <Row>
          <Col md={6}>
            <FormSelect
              control={control}
              name="customerId"
              label="Nhà cung cấp"
              placeholder="Mã - Tên NCC"
              options={suppliers?.data?.map(c => ({
                label: `${c?.code} - ${c?.name || ''}`,
                value: c?.id,
              }))}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="taxCode"
              label="MST"
              placeholder="MST"
              value={
                suppliers?.data?.find(c => c?.id === watch('customerId'))
                  ?.taxCode
              }
              disabled
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="address"
              label="Địa chỉ"
              placeholder="Địa chỉ"
              value={
                suppliers?.data?.find(c => c?.id === watch('customerId'))
                  ?.address
              }
              disabled
            />
          </Col>

          <Col md={6}>
            <FormInputV2
              control={control}
              name="shipper"
              label="Người giao"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={6}>
            <FormInputV2
              control={control}
              name="shipperPhone"
              label="Số điện thoại"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>
        </Row>

        <InventoriesConnect />

        <InventoriesItemsTable />

        <Row>
          <Col md={6}>
            <InventoriesPersonSign />
          </Col>
          <Col md={6}>
            <InventoriesAttachments />
          </Col>
        </Row>
      </Flex>
    </Form>
  );
};

export default InventoriesForm;
