package com.masi.utility.service.web.client;

import com.carevn.masi.service.TokenService;
import com.masi.utility.service.StandardWorkScheduleConfigService;
import com.masi.utility.service.dto.WorkScheduleQuery;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.Disposable;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.concurrent.TimeUnit;


@Slf4j
@Service
public class EmployeeCronjobClient {

    private final WebClient webClient;
    private final String HOST = "masiemployee";
    private final String EMPLOYEE_API = "/api/cron-job";
    private final String ENDPOINT;
    private final TokenService tokenService;
    private static ZonedDateTime timeEnd = ZonedDateTime.now();
    private static ZonedDateTime timeStart = timeEnd.minus(10, ChronoUnit.SECONDS);
    private final StandardWorkScheduleConfigService standardWorkScheduleConfigService;

    public EmployeeCronjobClient(@Qualifier("webClientConsul") WebClient webClient, TokenService tokenService, StandardWorkScheduleConfigService standardWorkScheduleConfigService) {

        this.webClient = webClient;
        ENDPOINT = "http://" + HOST + EMPLOYEE_API;
        this.tokenService = tokenService;
        this.standardWorkScheduleConfigService = standardWorkScheduleConfigService;
    }

    private Mono<String> getJwtToken() {

        return Mono.just(tokenService.getToken());
    }

    public Mono<Void> autoCreateTimeKeepingViolation() {
        return getJwtToken().flatMap(token -> webClient
                .post()
                .uri(ENDPOINT + "/auto-create-time-keeping-violation")
                .header("Authorization", "Bearer " + token)
                .retrieve()
                .bodyToMono(Void.class).onErrorResume(e -> {
                    log.error("Error in auto-update-data-time-keeping", e);
                    return Mono.empty();
                })
                .then());
    }

    public Mono<Void> autoLockTimeKeeping() {
        return getJwtToken().flatMap(token -> webClient
                .post()
                .uri(ENDPOINT + "/auto-lock-time-keeping")
                .header("Authorization", "Bearer " + token)
                .retrieve()
                .bodyToMono(Void.class)
                .onErrorResume(e -> {
                    log.error("Error in auto-update-data-time-keeping", e);
                    return Mono.empty();
                })
                .then());
    }
//    curl -X 'POST' \
//        'http://192.168.1.58:8080/services/masiemployee/api/shifts/auto-generate-daily-shifts-employee/abc/2014-10-10/3fa85f64-5717-4562-b3fc-2c963f66afa6,3fa85f64-5717-4562-b3fc-2c963f66afa6' \
//        -H 'accept: */*' \
//        -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4NGIzNmU4OS0xNTVlLTRjNGMtOWI2MS04NWNiYzhmNzM1ODkiLCJhdXRoIjoiUk9MRV9BRE1JTiBST0xFX1NVUEVSX0FETUlOIFJPTEVfVVNFUiIsImdyb3VwX2lkIjoiZGM4MDk1OWUtNGM2MS00NGQ1LThhMmEtZDlhMzY4NDEzYzBjIiwiY29tcGFueSI6IktJTV9MT05HIiwiZXhwIjoxNzMyMDc0NDE4LCJpYXQiOjE3Mjk0ODI0MTgsImdyb3VwIjoiS0hPXyZfTVVBX0hBTkcifQ.6ObYGPAyHe_sIOuLWLjy8rOzTWospDEz_rf-TKpQO2QzTfgNfyI4vHt7iTuBpo_GPueS2dHCJ-fPmDqbQRu9Aw' \
//        -d ''

//    public Mono<Void> autoGenerateDailyShiftsEmployee(String company, LocalDate date, Collection<UUID> shiftIds) {
//        String employeeIds = String.join(",", shiftIds.stream().map(UUID::toString).toArray(String[]::new));
//        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//        log.info("Post request to {}", "http://" + HOST + "/api/shifts/auto-generate-daily-shifts-employee/" + company + "/" + date.format(formatter) + "/" + employeeIds + "/" + "false");
//        return getJwtToken().flatMap(token -> webClient
//            .post()
//            .uri("http://" + HOST + "/api/shifts/auto-generate-daily-shifts-employee/" + company + "/" + date.format(formatter) + "/" + employeeIds + "/" + "false")
//            .header("Authorization", "Bearer " + token)
//            .retrieve()
//            .bodyToMono(Void.class)
//            .onErrorResume(e -> {
//                log.error("Error in auto-update-data-time-keeping", e);
//                return Mono.empty();
//            })
//            .then());
//    }

    @Scheduled(fixedRate = 60, timeUnit = TimeUnit.SECONDS)
    public Disposable testS() {
        List<String> company = List.of("KIM_LONG", "MMS");
        return Flux.fromIterable(company)
                .flatMap(c -> {
                    log.info("Auto create shift for company {}", c);
                    WorkScheduleQuery query = new WorkScheduleQuery();
                    query.setCompany(c);
                    query.setWorkspaceType("OFFICE");
                    LocalDate date = LocalDate.now().plusDays(3);
                    var dayOfWeek = date.getDayOfWeek().getValue();

                    return standardWorkScheduleConfigService.findByQuery(query)
                            .flatMapMany(e -> {
                                var sh = e.stream()
                                        .filter(f -> f.getDayOfWeek() == dayOfWeek)
                                        .findFirst()
                                        .orElse(null);
                                if (sh == null) {
                                    return Mono.empty();
                                }
                                log.info("Auto create shift for company {} at {} with dayofweek {}", c, date, dayOfWeek);
                                return autoGenerateDailyShiftsEmployee(c, date, List.of(sh.getId()));
                            })
                            .onErrorResume(e -> {
                                log.error("Error creating shifts for company {}: {}", c, e.getMessage());
                                return Mono.empty();  // Skip company on error
                            });
                })
                .subscribe();  // Subscribing to trigger the scheduled task
    }


    public Mono<Void> autoGenerateDailyShiftsEmployee(String company, LocalDate date, Collection<UUID> shiftIds) {
        Boolean override = false;
        String employeeIds = String.join(",", shiftIds.stream().map(UUID::toString).toArray(String[]::new));

        return getJwtToken().flatMap(token -> {
                    String uri = String.format(
                            "%s/auto-generate-daily-shifts-employee/%s/%s/%s",
                            ENDPOINT,
                            company,
                            employeeIds,
                            override
                    );

                    log.info("Generated URI: {}", uri);

                    Map<String, Object> requestBody = new HashMap<>();
                    requestBody.put("date", date.format(DateTimeFormatter.ISO_DATE));

                    return webClient
                            .post()
                            .uri(uri)
                            .header("Authorization", "Bearer " + token)
                            .accept(MediaType.ALL)
                            .contentType(MediaType.APPLICATION_JSON)
                            .bodyValue(requestBody)
                            .retrieve()
                            .bodyToMono(Void.class);
                });
    }





    public Mono<Void> autoCleanupOldDeletedContracts() {
        return getJwtToken().flatMap(token -> webClient
                .post()
                .uri(ENDPOINT + "/auto-cleanup-old-deleted-contracts")
                .header("Authorization", "Bearer " + token)
                .retrieve()
                .bodyToMono(Void.class)
                .onErrorResume(e -> {
                    log.error("Error in auto-update-data-time-keeping", e);
                    return Mono.empty();
                })
                .then());
    }


    // test //
//    @Scheduled(fixedRate = 5000)
    public void test() {
        ZonedDateTime timeEnd = ZonedDateTime.now(ZoneId.of("UTC"));
        timeStart = timeEnd.minusSeconds(20);
        updateDataTimeKeeping("jdbc:postgresql://192.168.1.19:5432/biosecurity-boot", "basso", "123123", timeStart, timeEnd).subscribe();
    }

    public Mono<Void> updateDataTimeKeeping(String urlDb, String userDb, String pwDb, ZonedDateTime timeStart, ZonedDateTime timeEnd) {
        return getJwtToken()
                .flatMap(token -> {
                    System.out.println("Updating time keeping data with parameters:");
                    System.out.println("URL DB: " + urlDb);
                    System.out.println("User DB: " + userDb);
                    System.out.println("Time Start: " + timeStart);
                    System.out.println("Time End: " + timeEnd);

                    Map<String, Object> bodyMap = new HashMap<>();
                    bodyMap.put("urlDb", Optional.ofNullable(urlDb).orElse(""));
                    bodyMap.put("userDb", Optional.ofNullable(userDb).orElse(""));
                    bodyMap.put("pwDb", Optional.ofNullable(pwDb).orElse(""));
                    bodyMap.put("timeStart", Optional.ofNullable(timeStart).map(ZonedDateTime::toString).orElse(""));
                    bodyMap.put("timeEnd", Optional.ofNullable(timeEnd).map(ZonedDateTime::toString).orElse(""));

                    return webClient
                            .post()
                            .uri(ENDPOINT + "/auto-update-data-time-keeping")
                            .header("Authorization", "Bearer " + token)
                            .bodyValue(bodyMap)  // Sử dụng map đã kiểm tra giá trị null
                            .retrieve()
                            .bodyToMono(Void.class)
                            .onErrorResume(e -> {
                                log.error("Error in auto-update-data-time-keeping", e);
                                return Mono.empty();
                            })
                            .then();
                });
    }


    //    @Scheduled(fixedRate = 86400)
    public Mono<Void> updateDataTimeKeepingOfEmployee(ZonedDateTime timeStart, ZonedDateTime timeEnd) {
        return getJwtToken()
                .flatMap(token -> {
                    System.out.println("Updating time keeping data with parameters:");
                    System.out.println("Time Start: " + timeStart);
                    System.out.println("Time End: " + timeEnd);
                    Map<String, Object> bodyMap = new HashMap<>();
                    bodyMap.put("timeStart", Optional.ofNullable(timeStart).map(ZonedDateTime::toString).orElse(""));
                    bodyMap.put("timeEnd", Optional.ofNullable(timeEnd).map(ZonedDateTime::toString).orElse(""));
                    return webClient
                            .post()
                            .uri(ENDPOINT + "/auto-update-data-timekeeping-of-employee")
                            .header("Authorization", "Bearer " + token)
                            .bodyValue(bodyMap)  // Sử dụng map đã kiểm tra giá trị null
                            .retrieve()
                            .bodyToMono(Void.class);
                });
    }

}
