import { zodResolver } from '@hookform/resolvers/zod';
import CardV2 from 'app/components/CardV2/CardV2';
import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT } from 'app/constants/common';
import { PATH } from 'app/constants/path';
import { useModalsAdvanceRequest } from 'app/hooks/use-advance-request';
import useEmployee from 'app/hooks/use-employee';
import usePaymentRequest from 'app/hooks/use-payment-request';
import { FORM } from 'app/shared/model/enumerations/form.model';
import {
  PAYMENT_REQUEST_STATUS,
  PAYMENT_REQUEST_TYPE,
} from 'app/shared/model/enumerations/payment-request';
import {
  AdvanceRequestSchema,
  advanceRequestSchema,
} from 'app/validation/request-payment.validation';
import dayjs from 'dayjs';
import { useEffect } from 'react';
import { FormProvider, SubmitHandler, useForm } from 'react-hook-form';
import { DateObject } from 'react-multi-date-picker';
import { useNavigate, useParams } from 'react-router';
import { ButtonGroupHeader } from '../components/ButtonGroupHeader';
import AdvanceRequestApproveModals from './advance-request-approve-modal';
import AdvanceRequestApproveSuccessModals from './advance-request-approve-success-modals';
import AdvanceRequestCancelModals from './advance-request-cancel-modals';
import AdvanceRequestCancelSuccessModals from './advance-request-cancel-success-modals';
import AdvanceRequestCreateSuccessModals from './advance-request-create-success-modals';
import AdvanceRequestForm from './advance-request-form';
import AdvanceRequestUpdateSuccessModals from './advance-request-update-success-modals';
import AuthGuard from 'app/components/guards/auth-guard';

const {
  usePostPaymentRequest,
  usePatchPaymentRequest,
  useGetPaymentRequestAutoGeneratedCode,
  useGetPaymentRequestById,
} = usePaymentRequest;
const { useGetEmployeesQuery } = useEmployee;

function AdvanceRequestCreateModals() {
  const navigate = useNavigate();
  const { id } = useParams();

  const account = useAppSelector(state => state.authentication.account);

  const [
    { openApprovalSign, toggleApprovalSign },
    { openApprovalSignSuccess, toggleApprovalSignSuccess },
    { openCancel, toggleCancel },
    { openCancelSuccess, toggleCancelSuccess },
    { openReject, toggleReject },
    { openRejectSuccess, toggleRejectSuccess },
    { openCreateSuccess, toggleCreateSuccess },
    { openUpdateSuccess, toggleUpdateSuccess },
  ] = useModalsAdvanceRequest();

  const methods = useForm<AdvanceRequestSchema>({
    defaultValues: {
      status: PAYMENT_REQUEST_STATUS.NEW,
      attachments: [],
      requestApprovals: [],
      paymentDetails: [],
      paymentDate: new DateObject(),
      createdDate: new DateObject(),
      createdByName: `${account?.lastName} ${account?.firstName}`,
    },
    resolver: zodResolver(advanceRequestSchema),
  });

  const { handleSubmit, setValue, reset, watch, formState } = methods;

  const statusWatch = watch('status');
  const createdByWatch = watch('createdBy');

  const { mutateAsync: create } = usePostPaymentRequest(toggleCreateSuccess);
  const { mutateAsync: update } = usePatchPaymentRequest(
    id,
    toggleUpdateSuccess,
  );

  const { data: employeeProfiles } = useGetEmployeesQuery();

  const { data: detail } = useGetPaymentRequestById(id);
  const { data: nextCode } = useGetPaymentRequestAutoGeneratedCode(
    PAYMENT_REQUEST_TYPE.ADVANCEMENT,
  );

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode)
        setValue('code', `TU${suffix}/${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  const onSubmit: SubmitHandler<AdvanceRequestSchema> = values => {
    if (!id) {
      create({
        code: undefined,
        order: undefined,
        type: PAYMENT_REQUEST_TYPE.ADVANCEMENT,
        attachments: values.attachments.map(x => ({
          fileId: x.fileId,
          fileName: x.fileName,
          createdAt: new Date(x.createdAt),
        })),
        totalAmount: Number(values.totalAmount),
        paidAmount: 0,
        paymentVoucher: values.paymentVoucher, // Phiếu chi
        paymentVoucherAmount: Number(values.paymentVoucherAmount), // Tổng tiền chi
        remainingAmount: 0,
        paymentDate: values.paymentDate.toDate(),
        note: values.note,
        content: values?.content,
        status: PAYMENT_REQUEST_STATUS.NEW,
        employeeId: values.employeeId,
        requestApprovals: values.requestApprovals
          ?.filter(x => x.employeeId)
          ?.map(x => ({
            index: x.index,
            employeeId: x.employeeId,
          })),
        paymentDetails: [],
      }).then(() => reset());
      return;
    } else {
      update({
        id: id ?? '',
        type: PAYMENT_REQUEST_TYPE.ADVANCEMENT,
        attachments: values.attachments.map(x => ({
          fileId: x.fileId,
          fileName: x.fileName,
          createdAt: new Date(x.createdAt),
        })),
        totalAmount: Number(values.totalAmount),
        paidAmount: 0,
        paymentVoucher: values.paymentVoucher, // Phiếu chi
        paymentVoucherAmount: Number(values.paymentVoucherAmount), // Tổng tiền chi
        remainingAmount: 0,
        paymentDate: values.paymentDate.toDate(),
        note: values.note,
        content: values?.content,
        status: PAYMENT_REQUEST_STATUS.NEW,
        employeeId: values.employeeId,
        requestApprovals: values.requestApprovals
          ?.filter(x => x.employeeId)
          ?.map(x => ({
            index: x.index,
            employeeId: x.employeeId,
          })),
        paymentDetails: [],
      });
    }
  };

  useEffect(() => {
    if (detail) {
      setValue('code', detail?.code);
      setValue('paymentDate', new DateObject(detail?.paymentDate));
      setValue('supplierCodeName', `${detail?.suppliers?.name}`);
      setValue('content', detail?.content);
      setValue('status', detail?.status);
      setValue('employeeId', detail?.employeeId);

      setValue(
        'reimbursementDate',
        detail?.reimbursementDate
          ? new DateObject(detail?.reimbursementDate)
          : undefined,
      );

      const empSelected = employeeProfiles?.data?.find(
        x => x.id === detail?.employeeId,
      );
      const empWorkspace = empSelected
        ? `${empSelected.workspace.normalizedName} - ${empSelected.workspace?.name}`
        : '';
      setValue('workspaceName', empWorkspace);

      setValue('requestApprovals', detail?.requestApprovals);
      setValue('totalAmount', `${detail?.totalAmount ?? 0}`);
      setValue('paymentVoucher', detail?.paymentVoucher);
      setValue('paymentVoucherAmount', `${detail?.paymentVoucherAmount ?? 0}`);
      setValue(
        'paymentDetails',
        detail?.paymentDetails?.map(x => ({
          ...x,
          id: x.id,
          incomingInvoice: {
            ...x.incomingInvoice,
            invoiceDate: new Date(x.incomingInvoice.invoiceDate).toISOString(),
          },
        })),
      );
      setValue(
        'attachments',
        detail?.attachments?.map(x => ({
          ...x,
          createdAt: new Date(x.createdAt),
        })),
      );
      setValue('createdDate', new DateObject(detail?.createdDate));

      const createdByName = [
        detail?.createdByEmployee?.employeeCode,
        detail?.createdByEmployee?.fullName,
      ].join(' - ');
      setValue('createdByName', createdByName);
      setValue('createdBy', detail?.createdBy);
    }
  }, [detail, employeeProfiles]);

  return (
    <>
      <FormProvider {...methods}>
        <Form id={FORM.CREATE_DNTU} onSubmit={handleSubmit(onSubmit)}>
          <CardV2
            header={
              <Flex justify="space-between" align="center">
                <Typography level={4}>DNTU</Typography>
                <AuthGuard permissionKey={!!id ? 'REQUEST_PAYMENT.EDIT' : 'REQUEST_PAYMENT.CREATE'}>
                  <ButtonGroupHeader
                    status={statusWatch}
                    createdBy={createdByWatch}
                    toggleCancel={toggleCancel}
                    toggleSendApprove={toggleApprovalSign}
                    disableSendApproved={detail?.requestApprovals?.length === 0}
                    type={PAYMENT_REQUEST_TYPE.ADVANCEMENT}
                  />
                </AuthGuard>
              </Flex>
            }
          >
            <AdvanceRequestForm />
          </CardV2>
        </Form>
      </FormProvider>

      <AdvanceRequestCreateSuccessModals
        isOpen={openCreateSuccess}
        toggle={() => {
          toggleCreateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <AdvanceRequestUpdateSuccessModals
        isOpen={openUpdateSuccess}
        toggle={() => {
          toggleUpdateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <AdvanceRequestApproveModals
        isOpen={openApprovalSign}
        selectedRecord={id}
        toggle={toggleApprovalSign}
        toggleSuccess={() => {
          toggleApprovalSign();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <AdvanceRequestApproveSuccessModals
        isOpen={openApprovalSignSuccess}
        toggle={() => {
          toggleApprovalSignSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <AdvanceRequestCancelModals
        isOpen={openCancel}
        toggle={toggleCancel}
        toggleSuccess={toggleCancelSuccess}
        selectedRecord={id}
      />

      <AdvanceRequestCancelSuccessModals
        isOpen={openCancelSuccess}
        toggle={() => {
          toggleCancelSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />
    </>
  );
}

export default AdvanceRequestCreateModals;
