package com.masi.employee.web.rest;

import com.masi.employee.service.ShiftService;
import com.masi.employee.service.TimeKeepingService;
import com.masi.employee.service.TimeKeepingViolationService;
import com.masi.employee.service.ZkbioTimeService;
import com.masi.employee.service.dto.cleanups.ContractCleanupScheduler;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Mono;

import javax.swing.filechooser.FileNameExtensionFilter;
import java.net.URISyntaxException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collection;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/cron-job")
@AllArgsConstructor
@Slf4j
public class CronJobResource {

    private final TimeKeepingViolationService timeKeepingViolationService;
    private final TimeKeepingService timeKeepingService;
    private final ContractCleanupScheduler contractCleanupScheduler;
    private final ZkbioTimeService zkbioTimeService;
    private final ShiftService shiftService;

    @PostMapping("/auto-create-time-keeping-violation")
    public ResponseEntity<Void> timeKeepingViolation() {
        log.info("Time keeping violation cron job started");
        Mono<Void> voidMono = timeKeepingViolationService.generateViolationRecord()
                .doOnError(e -> log.error("Error when generate violation record", e))
                .doAfterTerminate(() -> log.info("Time keeping violation cron job completed"));
        voidMono.subscribe();
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/auto-lock-time-keeping")
    public ResponseEntity<Void> timeKeeping() {
        log.info("Lock time keeping this week cron job started");
        Mono<Void> voidMono = timeKeepingService.lockTimeKeeping().doAfterTerminate(() -> log.info("Time keeping cron job completed"));
        voidMono.subscribe();
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/auto-cleanup-old-deleted-contracts")
    public ResponseEntity<Void> cleanupOldDeletedContracts() {
        log.info("Cleanup old deleted contracts cron job started");
        contractCleanupScheduler.cleanupOldDeletedContracts();
        log.info("Cleanup old deleted contracts cron job completed");
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/auto-update-data-time-keeping")
    public ResponseEntity<Void> updateDataTimeKeeping(@RequestBody Map<String, String> dbCredentials) {
        log.info("Update data time keeping cron job started");
        String urlDb = dbCredentials.get("urlDb");
        String userDb = dbCredentials.get("userDb");
        String pwDb = dbCredentials.get("pwDb");
        ZonedDateTime timeStart = ZonedDateTime.parse(dbCredentials.get("timeStart"));
        ZonedDateTime timeEnd = ZonedDateTime.parse(dbCredentials.get("timeEnd"));
        zkbioTimeService.saveTimeKeeping(urlDb, userDb, pwDb, timeStart, timeEnd)
                .doAfterTerminate(() -> log.info("Update data time keeping cron job completed"))
                .subscribe();
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/auto-update-data-timekeeping-of-employee")
    public ResponseEntity<Void> updateDataTimeKeepingOfEmployee(@RequestBody Map<String, String> dbCredentials) {
        log.info("Update data time keeping cron job started");
        ZonedDateTime timeStart = ZonedDateTime.parse(dbCredentials.get("timeStart"));
        ZonedDateTime timeEnd = ZonedDateTime.parse(dbCredentials.get("timeEnd"));

        Mono<Void> voidMono = zkbioTimeService.updateNameZkbioTime(timeStart, timeEnd)
                .doAfterTerminate(() -> log.info("Time keeping cron job completed"));
        voidMono.subscribe();
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/refresh-data-machine")
    public Mono<ResponseEntity<Void>> tesst() {
        log.info("Update data time keeping cron job started");
        ZonedDateTime TIME_START = ZonedDateTime.now(ZoneId.of("UTC")).minusDays(1);
        ZonedDateTime TIME_END = ZonedDateTime.now(ZoneId.of("UTC"));
        return zkbioTimeService.saveTimeKeeping(null, null, null, TIME_START, TIME_END)
                .then(Mono.just(ResponseEntity.noContent().build()));
    }


//    @PostMapping(value = "/auto-generate-daily-shifts-employee/{company}/{date}/{shiftIds}/{override}")
//    public Mono<ResponseEntity<Map>> autoGenerateDailyShiftsEmployee(
//            @PathVariable(value = "company", required = true) final String company,
//            @PathVariable(value = "shiftIds", required = true) final Collection<UUID> shiftIds,
//            @PathVariable(value = "date", required = true) final LocalDate date,
//            @PathVariable(value = "override", required = false) Boolean override
//    ) throws URISyntaxException {
//        log.info("REST request to auto generate daily shifts for company");
//        if (override == null) {
//            override = false;
//        }
//        return shiftService.autoGenerateDailyShiftsEmployee(company, shiftIds, date, override).map(apiResponse -> ResponseEntity.ok().body(apiResponse));
//    }
    @PostMapping(value = "/auto-generate-daily-shifts-employee/{company}/{shiftIds}/{override}")
    public Mono<ResponseEntity<Map>> autoGenerateDailyShiftsEmployee(
            @PathVariable(value = "company") final String company,
            @PathVariable(value = "shiftIds") final Collection<UUID> shiftIds,
            @PathVariable(value = "override", required = false) Boolean override,
            @RequestBody Map<String, String> requestBody
    ) {
        log.info("REST request to auto generate daily shifts for company");

        if (override == null) {
            override = false;
        }
        LocalDate date = LocalDate.parse(requestBody.get("date"), DateTimeFormatter.ISO_DATE);
        return shiftService.autoGenerateDailyShiftsEmployee(company, shiftIds, date, override)
                .map(apiResponse -> ResponseEntity.ok().body(apiResponse));
    }


//    @PostMapping(value = "/auto-generate-daily-shifts-employee/{company}/{shiftIds}/{override}")
//    public Mono<ResponseEntity<Map>> autoGenerateDailyShiftsEmployee(
//            @PathVariable(value = "company", required = true) final String company,
//            @PathVariable(value = "shiftIds", required = true) final Collection<UUID> shiftIds,
//            @PathVariable(value = "override", required = false) Boolean override
//    ) {
//        log.info("REST request to auto generate daily shifts for company");
//
//        if (override == null) {
//            override = false;
//        }
//        return shiftService.autoGenerateDailyShiftsEmployee(company, shiftIds, LocalDate.now(), override)
//                .map(apiResponse -> ResponseEntity.ok().body(apiResponse));
//    }




}
