import { paymentRequestEndpoins } from 'app/constants/endpoints';
import { PAYMENT_REQUEST_TYPE } from 'app/shared/model/enumerations/payment-request';
import { PaginationResponse } from 'app/shared/model/pagination.model';
import {
  IPatchPaymentRequestDto,
  IPaymentRequest,
  IPaymentRequestApproval,
  IPaymentRequestParams,
  IPaymentRequestReject,
  IPostPaymentRequestDto,
} from 'app/shared/model/payment-request.model';
import axios from 'axios';

export const getPaymentRequests =
  (params: IPaymentRequestParams) => async () => {
    const url = paymentRequestEndpoins.getPaymentRequests;
    return await axios.get<PaginationResponse<IPaymentRequest>>(url, {
      params,
      paramsSerializer: {
        indexes: null,
      },
    });
  };

const getPaymentRequestAutoGeneratedCode = async (
  type: PAYMENT_REQUEST_TYPE,
) => {
  try {
    const url = paymentRequestEndpoins.getPaymentRequestAutoGeneratedCode(type);
    const response = await axios.get<{
      code: string;
      next: string;
      nextAndIncrement: string;
    }>(url);
    return response;
  } catch (error) {
    console.error(error);
  }
};

const getPaymentRequestById = async (id: string) => {
  try {
    return await axios.get<IPaymentRequest>(
      paymentRequestEndpoins.getPaymentRequestById(id),
    );
  } catch (error) {
    console.error(error);
  }
};

const postPaymentRequest = async (data: IPostPaymentRequestDto) => {
  const url = paymentRequestEndpoins.postPaymentRequest;

  return await axios.post<IPaymentRequest>(url, data);
};

const patchPaymentRequest = async (
  data: IPatchPaymentRequestDto,
  id: string,
) => {
  const url = paymentRequestEndpoins.patchPaymentRequest(id);

  return await axios.patch<IPaymentRequest>(url, data);
};

const deletePaymentRequest = async (id: string) => {
  const url = paymentRequestEndpoins.deletePaymentRequest(id);

  return await axios.delete(url);
};

const cancelPaymentRequest = async (id: string) => {
  const url = paymentRequestEndpoins.cancelPaymentRequest(id);

  return await axios.patch<IPaymentRequest>(url);
};

const sendApprovePaymentRequest = async (id: string) => {
  const url = paymentRequestEndpoins.sendApprovePaymentRequest(id);

  return await axios.patch<IPaymentRequest>(url);
};

const getPaymentRequestReportsExcel = async () => {
  const url = paymentRequestEndpoins.exportExcelPaymentRequest();
  const response = await axios.get<string>(url, {
    params: {},
    responseType: 'blob',
    headers: {
      Accept: 'application/octet-stream',
    },
  });

  return response;
};

const approvePaymentRequest = async (
  data: IPaymentRequestApproval,
  id: string,
) => {
  const url = paymentRequestEndpoins.approvePaymentRequest(id);
  return await axios.patch<IPaymentRequestApproval>(url, data);
};

const rejectPaymentRequest = async (
  data: IPaymentRequestReject,
  id: string,
) => {
  const url = paymentRequestEndpoins.rejectPaymentRequest(id);
  return await axios.patch<IPaymentRequestReject>(url, data);
};

export default {
  getPaymentRequests,
  getPaymentRequestById,
  postPaymentRequest,
  patchPaymentRequest,
  deletePaymentRequest,
  getPaymentRequestAutoGeneratedCode,
  cancelPaymentRequest,
  sendApprovePaymentRequest,
  getPaymentRequestReportsExcel,
  approvePaymentRequest,
  rejectPaymentRequest,
};
