import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import FormSelect from 'app/components/form/form-select';
import FormDatePickerV2 from 'app/components/formV2/form-date/form-date-picker';
import FormInputV2 from 'app/components/formV2/form-input/form-input';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT, DEFAULT_PAGE_SIZE_NAX } from 'app/constants/common';
import useEmployee from 'app/hooks/use-employee';
import {
  useGetInventoriesAutoGeneratedCode,
  useInventoriesTypes,
  usePatchInventories,
  usePostInventories,
} from 'app/hooks/use-inventories';
import useWarehouse from 'app/hooks/use-warehouse';
import { FORM } from 'app/shared/model/enumerations/form.model';
import { InventoriesWarehouse } from 'app/shared/model/enumerations/warehouse.model';
import { INVENTORIES_STATUS } from 'app/shared/model/inventories-storage.model';
import { InventoriesExportSchema } from 'app/validation/inventories-export.validation';
import dayjs from 'dayjs';
import { useContext, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import { DateObject } from 'react-multi-date-picker';
import { useParams } from 'react-router';
import { useSearchParams } from 'react-router-dom';
import { Col, Row } from 'reactstrap';
import { InventoriesExportStorageContext } from '../inventories-storage-export-provider';
import InventoriesExportAttachments from './InventoriesExportAttachments';
import { InventoriesExportConnect } from './InventoriesExportConnects';
import { InventoriesExportCustomer } from './InventoriesExportCustomer';
import { InventoriesExportItemsTable } from './InventoriesExportItemsTable';
import InventoriesExportPersonSign from './InventoriesExportPersonSign';
import { InventoriesExportReceive } from './InventoriesExportReceive';

const { useGetWarehouses } = useWarehouse;

interface IInventoriesFormProps {
  type: 'create' | 'update';
}

const { useGetEmployeesQuery } = useEmployee;

const InventoriesForm = ({ type }: IInventoriesFormProps) => {
  const { id } = useParams();
  const [searchParams] = useSearchParams();
  const warehouseImportType = searchParams.get('warehouse');

  const account = useAppSelector(state => state.authentication.account);

  const { toggleCreateSuccess, toggleUpdateSuccess } = useContext(
    InventoriesExportStorageContext,
  );

  const { data: warehouses } = useGetWarehouses({
    size: DEFAULT_PAGE_SIZE_NAX,
  });
  const { data: inventoriesTypes } = useInventoriesTypes({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const { mutate: createInventories } = usePostInventories();
  const { mutate: updateInventories } = usePatchInventories(id);
  const { data: nextCode } = useGetInventoriesAutoGeneratedCode();
  const { data: employees, isLoading } = useGetEmployeesQuery({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const { control, handleSubmit, setValue, watch, reset, formState } =
    useFormContext<InventoriesExportSchema>();

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode) setValue('code', `${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  useEffect(() => {
    if (employees?.data?.length && account?.id && !id) {
      const selected = employees?.data?.find(x => `${x.id}` === account?.id);
      if (selected)
        setValue(
          'createdByName',
          `${selected?.code} - ${selected?.lastName} ${selected?.firstName}`,
        );
    }
  }, [employees]);

  const onSubmit = (values: InventoriesExportSchema) => {
    const inventoriesDetails = [
      ...values.inventoriesItemDetails,
      ...values.inventoriesMaterialDetails,
    ];

    const submitValues = {
      ...values,
      dateCreate: values.dateCreate.format(DATE_FORMAT.YEAR_DATE),
      createdAt: values.createdAt.format(DATE_FORMAT.YEAR_DATE),
      inventoriesDetails: inventoriesDetails.map(detail => ({
        ...detail,

        price: Number(detail.price),
        quantity: Number(detail.quantity),
        totalPrice: Number(detail.totalPrice),
        code: detail.code,
        // Xuất kho

        vatId: detail?.vatId,
        vatRate: Number(detail?.vatRate),
        vatAmount: Number(detail?.vatAmount),
        registerDate: detail?.registerDate
          ? new DateObject(detail?.registerDate).toDate()
          : undefined,
        depreciationDate: detail?.depreciationDate
          ? new DateObject(detail?.depreciationDate).toDate()
          : undefined,
        departmentId: detail?.departmentId,
        usageMonth: Number(detail?.usageMonth),
        holder: detail?.holder,
        depreciationAllocation: detail?.depreciationAllocation,
        expenseAccount: detail?.expenseAccount,
        costElements: detail?.costElements,
        unitPrice: Number(detail?.unitPrice),
      })),
      file: values.file?.map(f => ({
        fileId: f.fileId,
        fileName: f.fileName,
        createdAt: f.createdAt,
      })),
      attribute: {
        shipper: values.shipper,
        shipperAddress: values.shipperAddress,
        receiverName: values.receiverName,
        receiverPhone: values.receiverPhone,

        workspaceId: values.workspaceId,
      },
      totalAmount: inventoriesDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.price || 0) * Number(item?.quantity || 0);
        return acc;
      }, 0),
      totalQuantity: inventoriesDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.quantity);
        return acc;
      }, 0),
      requestApprovals: values.isNoReview
        ? []
        : values.requestApprovals
            ?.filter(x => x.employeeId)
            ?.map(x => ({
              index: x.index,
              employeeId: x.employeeId,
            })),
      status: INVENTORIES_STATUS.NEW,
      warehouseGroupType:
        searchParams.get('warehouse') ??
        InventoriesWarehouse?.WAREHOUSE_DEPRECIATION_EXPORT,
      isReview: !values.isNoReview,
    };

    if (type === 'update') {
      updateInventories(submitValues, {
        onSuccess: () => {
          toggleUpdateSuccess();
          reset();
        },
      });
      return;
    }

    createInventories(submitValues, {
      onSuccess: () => {
        toggleCreateSuccess();
        reset();
      },
    });
  };

  const disabled =
    watch('status') === (INVENTORIES_STATUS.WAITING_APPROVED as string) ||
    watch('status') === (INVENTORIES_STATUS.CANCELLED as string) ||
    watch('status') === (INVENTORIES_STATUS.APPROVED as string) ||
    watch('status') === (INVENTORIES_STATUS.COMPLETED as string);

  return (
    <Form id={FORM.INVENTORIES} onSubmit={handleSubmit(onSubmit)}>
      <Flex direction="column" gap={20}>
        <Typography level={5}>Thông tin chung</Typography>
        <Row>
          <Col md={3}>
            <FormInputV2
              control={control}
              name="code"
              label="Mã phiếu"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="incomingWarehouseId"
              label="Kho"
              options={warehouses?.data?.map(w => ({
                label: `${w?.code} - ${w?.name}`,
                value: w?.id,
              }))}
              placeholder="Chọn"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="inventoriesTypeId"
              label="Loại xuất"
              options={inventoriesTypes?.data?.map(it => ({
                label: `${it?.code} - ${it?.name}`,
                value: it?.id,
              }))}
              placeholder="Chọn loại xuất"
              disabled={type === 'update'}
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="dateCreate"
              label="Ngày xuất kho"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormSelect
              control={control}
              name="employeeId"
              label="Nhân viên"
              placeholder="Mã - Tên nhân viên"
              options={employees?.data?.map(e => ({
                label: `${e.code} - ${e.employeeProfile?.fullName}`,
                value: e?.id,
              }))}
              isLoading={isLoading}
              onChanges={e => {
                const selected = employees?.data?.find(x => `${x.id}` === e);
                if (selected)
                  setValue(
                    'workspaceName',
                    `${selected?.workspace?.normalizedName} - ${selected?.workspace?.name}`,
                  );
              }}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="workspaceName"
              label="Bộ phận"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="createdByName"
              label="Người tạo"
              placeholder="Mã - Tên nhân viên"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              name="createdAt"
              label="Ngày lập phiếu"
              disabled
            />
          </Col>

          <Col md={12}>
            <FormInputV2
              control={control}
              name="note"
              label="Diễn giải"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>
        </Row>

        <InventoriesExportCustomer />
        <InventoriesExportConnect />
        <InventoriesExportItemsTable />

        <Row>
          <Col md={6}>
            <InventoriesExportPersonSign />
          </Col>
          <Col md={6}>
            <InventoriesExportAttachments />
          </Col>
        </Row>
      </Flex>
    </Form>
  );
};

export default InventoriesForm;
