export enum ALLOCATION_TYPE {
  INTERNAL = 'INTERNAL',
  OUTSIDE = 'OUTSIDE',
  CUSTOMER = 'CUSTOMER',
  EMPLOYEE = 'EMPLOYEE',
  OTHER = 'OTHER',
}

export enum ALLOCATION_STATUS {
  UNPROCESSED = 'UNPROCESSED',
  WAITING_FOR_PROCESSING = 'WAITING_FOR_PROCESSING',
  PROCESSED = 'PROCESSED',
  CANCEL = 'CANCEL',
  SUCCESS = "SUCCESS"
}
