export enum AUTHORITIES_ACTIONS {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  REVIEW = 'REVIEW',
  EXPORT = 'EXPORT',
  CREATE_MANY = 'CREATE_MANY',
  CANCEL = 'CANCEL',
  ADJOURN = 'ADJOURN',
  MIX_CHECKING = 'MIX_CHECKING',
  START = 'START',
  PROPOSE_APPROVE = 'PROPOSE_APPROVE',
}

export const actions_count = {
  [AUTHORITIES_ACTIONS.READ]: 0,
  [AUTHORITIES_ACTIONS.CREATE]: 0,
  [AUTHORITIES_ACTIONS.UPDATE]: 0,
  [AUTHORITIES_ACTIONS.DELETE]: 0,
  [AUTHORITIES_ACTIONS.CANCEL]: 0,
  [AUTHORITIES_ACTIONS.REVIEW]: 0,
  [AUTHORITIES_ACTIONS.EXPORT]: 0,
  [AUTHORITIES_ACTIONS.CREATE_MANY]: 0,
  [AUTHORITIES_ACTIONS.ADJOURN]: 0,
  [AUTHORITIES_ACTIONS.MIX_CHECKING]: 0,
  [AUTHORITIES_ACTIONS.START]: 0,
  [AUTHORITIES_ACTIONS.PROPOSE_APPROVE]: 0,
}

export const action_arr = [
  AUTHORITIES_ACTIONS.READ,
  AUTHORITIES_ACTIONS.CREATE,
  AUTHORITIES_ACTIONS.UPDATE,
  AUTHORITIES_ACTIONS.DELETE,
  AUTHORITIES_ACTIONS.CANCEL,
  AUTHORITIES_ACTIONS.REVIEW,
  AUTHORITIES_ACTIONS.EXPORT,
  AUTHORITIES_ACTIONS.CREATE_MANY,
  AUTHORITIES_ACTIONS.ADJOURN,
  AUTHORITIES_ACTIONS.MIX_CHECKING,
  AUTHORITIES_ACTIONS.START,
  AUTHORITIES_ACTIONS.PROPOSE_APPROVE,
];

export const authories_arr_length = action_arr.length;

export enum AUTHORITIES_NAME {
  EMPLOYEE = 'employee',
  LEAVE_REGIME_REQUEST = 'leave_regime_request',
  ANNUAL_LEAVE = 'annual_leave',
  RECRUITMENT_REQUEST = 'recruitment_request',
  INTERVIEW_SCHEDULE = 'interview_schedule',
  UNIFORM_ORDER = 'uniform_order',
  UNIFORM_ORDER_STOCK = 'uniform_order_stock',
  UNIFORM_RELEASE = 'uniform_release',
  REPORT = 'REPORT',
  PERMISION = 'PERMISION',
  WORKSPACE = 'WORKSPACE',
  TIME_KEEPING = 'time_keeping',
  PERSONAL_MONTHLY_TIMESHEET = 'personal_monthly_timesheet',
  TIME_KEEPING_VIOLATION = 'time_keeping_violation',
  EXPLANATION_REVIEW = 'explanation_review',
  TIME_KEEPING_EXPLANATION = 'time_keeping_explanation',
  LEAVE_REQUEST = 'leave_request',
  CUSTOMER = 'customer',
  QUOTATION = 'quotation',
  CONTRACT = 'contract',
  PURCHASE_REQUEST = 'purchase_request',
  ORDER = 'order',
  ACCOUNT = 'ACCOUNT',
  WORK_CENTER = 'work_center',
  PRODUCT_STANDARD = 'product_standard',
  PRODUCT_ROUTING = 'product_routing',
  PRODUCT_MAINTENANCE = 'product_maintenance',
  SAMPLE_DISPOSAL = 'sample_disposal',
  QUANLITY_CHECK_SAMPLE = 'quality_check_sample',
  PRODUCT_PACKAGE = 'product_package',
  WORK_ORDER = 'work_order',
  MANUFACTURER_ORDER = 'manufacturer_order',
  INCOMING_INVOICE = 'incoming-invoice',
  SUPPLIERS_REQUESTS = 'supplies-request',
  SUPPLIERS = 'suppliers',
  SUPPLIERS_GROUPS = 'suppliers-groups',
  USERS_SETTING = 'users-setting',
  ANNUAL_LEAVE_SETTING = 'annual-leave-setting',
  UOM_SETTING = 'uom-setting',
  ITEMS_SETTING = 'items-settings',
  UNIFORM_SETTING = 'uniform-settings',
  CONTACT = 'contact',
  RECRUITMENT = 'recruitment',
  LEAVE_REGISTER = 'leave-register',
  SUPPLIES_REQUESTS = 'supplies-requests',
  QUOTATIONS = 'quotations',
  ORDERS = 'orders',
  CONTRACTS = 'contracts',
  SUPPLIES = 'supplies',
}
