export enum ECAll_CENTER_TYPE {
  INTERNAL = 'INTERNAL',
  OUTSIDE = 'OUTSIDE',
  CUSTOMER = 'CUSTOMER',
  EMPLOYEE = 'EMPLOYEE',
  OTHER = 'OTHER',
}

export enum ECAll_CENTER_STATUS {
  UNPROCESSED = 'UNPROCESSED',
  WAITING_FOR_PROCESSING = 'WAITING_FOR_PROCESSING',
  PROCESSED = 'PROCESSED',
  CANCEL = 'CANCEL',
  SUCCESS = 'SUCCESS',
}

export enum CALL_CENTER_SOURCE {
  EMAIL = 'EMAIL',
  CALL = 'SĐT',
  OTHER = 'OTHER',
}

export enum CALL_CENTER_GROUP {
  EMPLOYEE = 'EMPLOYEE',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}

export enum CALL_CENTER_TYPE {
  COMPLAINT = 'COMPLAINT',
  REQUEST = 'REQUEST',
  OTHER = 'OTHER',
}

export enum CALL_CENTER_STATUS {
  NEW = 'NEW',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
}

export enum CALL_CENTER_TYPE_PAGE {
  CALL_CENTER = 'CALL_CENTER',
  COMPLAINT = 'COMPLAINT',
}
