export enum CONTRACT_STATUS {
  DRAFT = 'DRAFT',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  FINISHED = 'FINISHED',
  WAITING_LIQUIDATION = 'WAITING_LIQUIDATION',
  LIQUIDATED = 'LIQUIDATED',
  CANCELLED = 'CANCELLED',
  DELETED = 'DELETED',
  LIQUIDATE_CANCELLED = 'LIQUIDATE_CANCELLED',
  REJECTED = 'REJECTED'
}

export enum CONTRACT_TYPE {
  NEW = 'NEW',
  PRICE_UP = 'PRICE_UP',
  PRICE_DOWN = 'PRICE_DOWN',
  EXTEND = 'EXTEND',
  ADDITIONAL_CONTRACT_INDEX = 'ADDITIONAL_CONTRACT_INDEX',
  SALES = 'SALES',
}

export enum EPayCondition {
  CFR = 'CFR',
  'D/P' = 'D/P',
  'T/T' = 'T/T',
  FOB = 'FOB',
  CIF = 'CIF',
  CK = 'CK',
  TM = 'TM',
}
