export enum DOCUMENTARY_GROUP {
  OUTGOING = 'OUTGOING',
  INCOMING = 'INCOMING',
  INTERNAL = 'INTERNAL',
}

export enum DOCUMENTARY_TYPE {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  DOCUMENTARY = 'DOCUMENTARY',
  RESPONSE = 'RESPONSE',
}

export enum DOCUMENTARY_STATUS {
  NEW = 'NEW',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REQUEST_EDIT = 'REQUEST_EDIT',
}
