export enum LEAVE_REQUEST_STATUS {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
}

export enum LEAVE_REQUEST_TYPE {
  SICK_LEAVE = 'SICK_LEAVE',
  ANNUAL_LEAVE = 'ANNUAL_LEAVE',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  UNPAID_LEAVE = 'UNPAID_LEAVE',
  FUNERAL_LEAVE = 'FUNERAL_LEAVE',
  WEDDING_LEAVE = 'WEDDING_LEAVE',
  COMPENSATION_LEAVE = 'COMPENSATION_LEAVE',
}

export enum LEAVE_REQUEST_DAY_TYPE {
  FULL_DAY = 'FULL_DAY',
  HALF_DAY = 'HALF_DAY',
}

export enum LEAVE_REQUEST_SHIFT_TYPE {
  MORNING_SHIFT = 'MORNING_SHIFT',
  AFTERNOON_SHIFT = 'AFTERNOON_SHIFT',
}