export enum LOGISTICS_MATERIAL_RPOPOSAL_STATUS {
    NEW = 'NEW',
    WAITING_APPROVAL = 'WAITING_APPROVAL',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    IS_DELIVERING = 'IS_DELIVERING',
    COMPLETED = 'COMPLETED',
}