export enum ORDER_STATUS {
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  NOT_APPROVE = 'NOT_APPROVE',
  WAITING = 'WAITING',
  REJECTED = 'REJECTED',
  DELETED = 'DELETED',
  NEW = 'NEW',
  CANCELLED = 'CANCELLED',
  NOT_DELIVERED = 'NOT_DELIVERED',
  IN_PROGRESS_DELIVERED = 'IN_PROGRESS_DELIVERED',
  FINISHED = 'FINISHED',
}

export enum ORDER_REVIEW_SOLUTION {
  REJECT = 'REJECT',
  WAITING = 'WAITING',
}
