export enum PAYMENT_REQUEST_TYPE {
  PAYMENT = 'PAYMENT',
  ADVANCEMENT = 'ADVANCEMENT',
  REIMBURSEMENT = 'REIMBURSEMENT',
}

export enum PAYMENT_REQUEST_STATUS {
  NEW = 'NEW',
  WAITING_APPROVE = 'WAITING_APPROVE',
  WAITING_APPROVED = 'WAITING_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
