export enum PRODUCTION_COMMAND_STATUS {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  NEW = 'NEW',
  COMPLETE_PRODUCTION = 'COMPLETE_PRODUCTION',
  TRANSPORTING = 'TRANSPORTING',
  WAREHOUSED = 'WAREHOUSED',
  PAUSED = 'PAUSED',
}

export enum PRODUCTION_COMMAND_TYPE {
  MANUFACTURE_ORDER_BY_ORDER = 'MANUFACTURE_ORDER_BY_ORDER',
  MANUFACTURE_ORDER_BY_STANDARD = 'MANUFACTURE_ORDER_BY_STANDARD',
}

export enum PRODUCTION_COMMAND_STANDARD_STATUS {
  VALID = 'VALID',
  EXPIRED = 'EXPIRED',
}

export enum MANUFACTURE_ORDER_STATUS {
  NEW = 'NEW',
  MATERIAL = 'MATERIAL',
  ADDITIVES = 'ADDITIVES',
  PRODUCTION = 'PRODUCTION',
  PACKAGING = 'PACKAGING',
  PACKED_COMPLETED = 'PACKED_COMPLETED',
  SHIPPED = 'SHIPPED',
  COMPLETED = 'COMPLETED',
  WAREHOUSED = 'WAREHOUSED',
  CANCELLED = 'CANCELLED',
}

export enum MANUFACTURE_ORDER_TYPE {
  MANUFACTURE_ORDER_BY_ORDER = 'MANUFACTURE_ORDER_BY_ORDER',
  MANUFACTURE_ORDER_BY_STANDARD = 'MANUFACTURE_ORDER_BY_STANDARD',
}
