export enum PURCHASE_STATUS {
  NEW = 'NEW',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DELIVERING = 'DELIVERING',
  FINISHED = 'FINISHED',
}

export enum PURCHASE_UNIT {
  KG = 'KG',
  TON = 'TON',
  PIECE = 'PIECE',
}
