export enum QUOTATION_STATUS {
  NEW = 'NEW',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  CUSTOMER_APPROVED = 'CUSTOMER_APPROVED',
  NEED_UPDATE = 'NEED_UPDATE',
  SENT = 'SENT',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
