export enum RECRUITMENT_POSITION {
  EMPLOYEE = 'EMPLOYEE',
  TEAM_LEADER = 'TEAM_LEADER',
  SUPERVISOR = 'SUPERVISOR',
  DIRECTOR = 'DIRECTOR',
}

export enum GENDER {
  FEMALE = 'FEMALE',
  MALE = 'MALE',
  NO_REFERENCE = 'NO_REFERENCE',
}

export enum RECRUITMENT_STATUS {
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WAITING_INTERVIEW = 'WAITING_INTERVIEW',
  COMPLETED = 'COMPLETED',
  WAITING_RENEW = 'WAITING_RENEW',
}

export enum RECRUITMENT_CONTRACT_TYPE {
  TRIAL = 'TRIAL',
  FIXED_TERM = 'FIXED_TERM',
  UNDEFINED_TERM = 'UNDEFINED_TERM',
  SEASONAL = 'SEASONAL',
}

export enum RECRUITMENT_PROCESS {
  WAITING_INTERVIEW = 'WAITING_INTERVIEW',
  INTERVIEWED = 'INTERVIEWED',
}

export enum INTERVIEW_RESULT {
  PASS = 'PASS',
  FAIL = 'FAIL',
  HOLD = 'HOLD',
}

export enum INTERVIEW_MODE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}
