export enum TIME_KEEPING_VIOLATION_TYPE {
  ABSENT_WITHOUT_REQUEST = 'ABSENT_WITHOUT_REQUEST',
  INSUFFICIENT_WORKING_TIME = 'INSUFFICIENT_WORKING_TIME',
  OVERTIME = 'OVERTIME',
  MISSING_CHECKOUT = 'MISSING_CHECKOUT',
  NO_VIOLATION = 'NO_VIOLATION',
}
