export enum TIME_KEEPING_MONTHLY_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TIME_KEEPING_MONTHLY_REVIEW {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
