export enum TIME_KEEPING_EXPLANATION_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TIME_KEEPING_EXPLANATION_REASON {
  ABSENT_WITHOUT_REQUEST = 'ABSENT_WITHOUT_REQUEST',
  INSUFFICIENT_WORKING_TIME = 'INSUFFICIENT_WORKING_TIME',
  OVERTIME = 'OVERTIME',
  MISSING_CHECKOUT = 'MISSING_CHECKOUT',
  NO_VIOLATION = ' NO_VIOLATION',
}

export enum TIME_KEEPING_EXPLANATION_REVIEW_STATUS {
  APPROVED = 'APPROVED',
  AWAITING_REVIEW = 'AWAITING_REVIEW',
  REJECTED = 'REJECTED',
}
