export enum UNIFORM_ORDER_STATUS {
  WAITING = 'WAITING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  STOCKED = 'STOCKED',
  PROCESSING = 'PROCESSING',
}

export enum UNIFORM_RELEASE_TYPE {
  SALE = 'SALE',
  SUPPORT = 'SUPPORT',
  SENIORITY = 'SENIORITY',
  OTHER = 'OTHER',
}

export enum UNIFORM_REPORT_TYPE {
  STOCKED = 'STOCKED',
  STOCK = 'STOCK',
  RELEASE = 'RELEASE',
}

export enum UNIFORM_STATUS {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
}
