export enum InventoriesWarehouse {
  WAREHOUSE_COMMERCE_IMPORT = 'WAREHOUSE_COMMERCE_IMPORT',
  WAREHOUSE_COMMERCE_EXPORT = 'WAREHOUSE_COMMERCE_EXPORT',
  WAREHOUSE_DEPRECIATION_IMPORT = 'WAREHOUSE_DEPRECIATION_IMPORT',
  WAREHOUSE_DEPRECIATION_EXPORT = 'WAREHOUSE_DEPRECIATION_EXPORT',
}
