import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import FormSelect from 'app/components/form/form-select';
import FormDatePickerV2 from 'app/components/formV2/form-date/form-date-picker';
import FormInputV2 from 'app/components/formV2/form-input/form-input';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT, DEFAULT_PAGE_SIZE_NAX } from 'app/constants/common';
import useEmployee from 'app/hooks/use-employee';
import useSupplier from 'app/hooks/use-supplier';
import {
  useGetSupplierContractsAutoGeneratedCode,
  usePatchSupplierContracts,
  usePostSupplierContracts,
} from 'app/hooks/use-supplier-contract';
import { FORM } from 'app/shared/model/enumerations/form.model';
import { SUPPLIER_CONTRACT_STATUS } from 'app/shared/model/supplier-contract.model';
import { SupplierContractsSchema } from 'app/validation/supplier-contracts.validation';
import dayjs from 'dayjs';
import { useContext, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import { useParams } from 'react-router';
import { useSearchParams } from 'react-router-dom';
import { Col, Row } from 'reactstrap';
import { SupplierContractsContext } from '../supplier-contracts-storage-provider';
import SupplierContractsAttachments from './SupplierContractAttachments';
import { SupplierContractsConnect } from './SupplierContractConnects';
import { SupplierContractsItemsTable } from './SupplierContractItemsTable';
import { SupplierContractsStatusOptions } from '../supplier-contracts-mapping';

const { useGetSuppliers } = useSupplier;

interface ISupplierContractsFormProps {
  type: 'create' | 'update';
}

const { useGetEmployeesQuery } = useEmployee;

const SupplierContractsForm = ({ type }: ISupplierContractsFormProps) => {
  const { id } = useParams();
  const [searchParams] = useSearchParams();

  const account = useAppSelector(state => state.authentication.account);

  const { toggleCreateSuccess, toggleUpdateSuccess } = useContext(
    SupplierContractsContext,
  );

  const { data: suppliers } = useGetSuppliers();

  const { mutate: createSupplierContracts } = usePostSupplierContracts();
  const { mutate: updateSupplierContracts } = usePatchSupplierContracts(id);
  const { data: nextCode } = useGetSupplierContractsAutoGeneratedCode();
  const { data: employees, isLoading } = useGetEmployeesQuery({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const { control, handleSubmit, setValue, watch, reset, formState } =
    useFormContext<SupplierContractsSchema>();
  const statusWatch = watch('status');

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      setValue("status", SUPPLIER_CONTRACT_STATUS.NEW);
      if (nextCode)
        setValue('contractCode', `HDM${suffix}/${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  useEffect(() => {
    if (employees?.data?.length && account?.id && !id) {
      const selected = employees?.data?.find(x => `${x.id}` === account?.id);
      if (selected)
        setValue(
          'createdByName',
          `${selected?.code} - ${selected?.lastName} ${selected?.firstName}`,
        );
    }
  }, [employees]);

  const onSubmit = (values: SupplierContractsSchema) => {
    const submitValues = {
      ...values,
      contractDate: dayjs(values?.contractDate.toDate()).format(
        DATE_FORMAT.YEAR_DATE,
      ),
      deliveryEstDate: dayjs(values?.deliveryEstDate.toDate()).format(
        DATE_FORMAT.YEAR_DATE,
      ),
      startDate: dayjs(values?.startDate.toDate()).format(
        DATE_FORMAT.YEAR_DATE,
      ),
      endDate: dayjs(values?.endDate.toDate()).format(DATE_FORMAT.YEAR_DATE),
      contractAmount: Number(values?.contractAmount ?? 0),
      paymentTermNumber: Number(values?.paymentTermNumber ?? 0),

      note: values?.note,
      suppliesRequestId: values?.suppliesRequestId,

      supplierContractDetails: values.supplierContractDetails.map(detail => ({
        ...detail,
        supplyItemId: detail.itemId,
        unitId: detail.uomId,
        price: Number(detail.price),
        quantity: Number(detail.quantity),
        totalAmount: Number(detail.totalPrice),
        totalPrice: Number(detail.totalPrice),
        code: detail.code,
      })),
      attachments: values.attachments?.map(f => ({
        fileId: f.fileId,
        fileName: f.fileName,
        createdAt: f.createdAt,
      })),
      totalAmount: values?.supplierContractDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.price || 0) * Number(item?.quantity || 0);
        return acc;
      }, 0),
      totalAmountAfterTax: values?.supplierContractDetails?.reduce(
        (acc, item) => {
          acc =
            acc +
            Number(item?.price || 0) * Number(item?.quantity || 0) +
            Number(item.vatAmount ?? 0);
          return acc;
        },
        0,
      ),
      totalQuantity: values?.supplierContractDetails?.reduce((acc, item) => {
        acc = acc + Number(item?.quantity);
        return acc;
      }, 0),
      requestApprovals: values.requestApprovals
        ?.filter(x => x.employeeId)
        ?.map(x => ({
          index: x.index,
          employeeId: x.employeeId,
        })),
      liquidationRequestApprovals: values.liquidationRequestApprovals
        ?.filter(x => x.employeeId)
        ?.map(x => ({
          index: x.index,
          employeeId: x.employeeId,
        })),
      status: values.status,
      createdAt: undefined,
    };

    if (type === 'update') {
      updateSupplierContracts(submitValues, {
        onSuccess: () => {
          toggleUpdateSuccess();
          reset();
        },
      });
      return;
    }

    createSupplierContracts(submitValues, {
      onSuccess: () => {
        toggleCreateSuccess();
        reset();
      },
    });
  };

  const disabled = false;
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.WAITING_APPROVE as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.CANCELLED as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.APPROVED as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.COMPLETED as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.WAITING_LIQUIDATION as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.REJECTED_LIQUIDATION as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.EXPIRED as string) ||
    // statusWatch === (SUPPLIER_CONTRACT_STATUS.LIQUIDATED as string);

  return (
    <Form id={FORM.SUPPLIER_CONTRACTS} onSubmit={handleSubmit(onSubmit)}>
      <Flex direction="column" gap={20}>
        <Typography level={5}>Thông tin chung</Typography>
        <Row>
          <Col md={3}>
            <FormInputV2
              control={control}
              name="contractCode"
              label="Mã phiếu"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="contractDate"
              label="Ngày lập"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="startDate"
              label="Ngày bắt đầu"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="endDate"
              label="Ngày kết thúc"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="paymentTermNumber"
              label="Thời hạn thanh toán"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="contractAmount"
              label="Giá trị hợp đồng (VND)"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="deliveryEstDate"
              label="Ngày giao dự kiến"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={type === 'update'}
            />
          </Col>
          <Col md={3}>
            <FormSelect
              control={control}
              name="status"
              label="Trạng thái"
              placeholder="Chọn trạng thái"
              isClearable={false}
              options={SupplierContractsStatusOptions?.map(c => ({
                label: `${c?.label}`,
                value: c?.value,
              }))}
            />
          </Col>

          <Col md={12}>
            <FormInputV2
              control={control}
              name="note"
              label="Diễn giải"
              placeholder="Vui lòng nhập diễn giải"
              disabled={disabled}
            />
          </Col>
        </Row>

        <Typography level={5}>NCC</Typography>
        <Row>
          <Col md={3}>
            <FormSelect
              control={control}
              name="supplierId"
              label="Nhà cung cấp"
              placeholder="Mã - Tên NCC"
              options={suppliers?.data?.map(c => ({
                label: `${c?.code} - ${c?.name || ''}`,
                value: c?.id,
              }))}
              disabled={disabled}
              onChanges={e => {
                const selected = suppliers?.data?.find(x => x.id === e);
                if (selected) {
                  setValue('supplierTaxCode', selected?.taxCode);
                  setValue('supplierAddress', selected?.address);
                }
              }}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="supplierTaxCode"
              label="MST"
              placeholder="MST"
              disabled
            />
          </Col>

          <Col md={6}>
            <FormInputV2
              control={control}
              name="supplierAddress"
              label="Địa chỉ"
              placeholder="Địa chỉ"
              disabled
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="supplierFullName"
              label="Người đại diện"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="supplierPosition"
              label="Chức vụ"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="supplierPhone"
              label="Số điện thoại"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>

          <Col md={3}>
            <FormInputV2
              control={control}
              name="supplierEmail"
              label="Email"
              placeholder="Điền"
              disabled={disabled}
            />
          </Col>
        </Row>

        <SupplierContractsConnect />

        <SupplierContractsItemsTable />

        <Row>
          <Col md={6}>
            <SupplierContractsAttachments />
          </Col>
        </Row>
      </Flex>
    </Form>
  );
};

export default SupplierContractsForm;
