version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mrp-web
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./deploy/nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - ./webpack/environment.staging.js:/webpack/environment.js