import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MUTATION_KEY, QUERY_KEY } from 'app/constants/query-key';
import {
  confirmImportInventories,
  confirmInventories,
  deleteInventories,
  getInventories,
  getInventoriesById,
  getInventoriesGeneratedCode,
  getInventoriesStorageItems,
  getInventoriesStorageItemsAllByWarehouse,
  getInventoriesTypes,
  getInventoriesXlsx,
  patchInventories,
  postInventories,
  rejectInventories,
  reviewInventories,
} from 'app/services/inventories-storage.service';
import {
  IInventoriesStorage,
  IInventoriesStorageParams,
  IInventoriesTypeParams,
} from 'app/shared/model/inventories-storage.model';
import { PaginationParams } from 'app/shared/model/pagination.model';
import { useState } from 'react';

export const useInventories = (filter?: IInventoriesStorageParams) => {
  return useQuery({
    queryKey: [QUERY_KEY.INVENTORIES, filter],
    queryFn: () => getInventories(filter),
    select: data => data.data,
    placeholderData: old => old,
  });
};

export const useInventoriesExportXlsxLazyQuery = (
  filter?: IInventoriesStorageParams,
) => {
  const queryClient = useQueryClient();
  const [enabled, setEnabled] = useState(false);

  const query = useQuery({
    queryKey: [QUERY_KEY.INVENTORIES_EXPORT, filter],
    queryFn: () => getInventoriesXlsx(filter),
    enabled,
  });

  const trigger = () => {
    setEnabled(true);
  };

  if (query.isSuccess) {
    queryClient.resetQueries({
      queryKey: [QUERY_KEY.INVENTORIES_EXPORT],
    });
  }

  if ((query.isSuccess || query.isError) && enabled) {
    setEnabled(false);
  }

  return { trigger, ...query };
};

export const useInventoriesTypes = (filter?: IInventoriesTypeParams) => {
  return useQuery({
    queryKey: [QUERY_KEY.INVENTORIES_TYPES],
    queryFn: () => getInventoriesTypes(filter),
    select: data => data.data,
  });
};

export const usePostInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.CREATE_INVENTORIES],
    mutationFn: postInventories,
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const usePatchInventories = (id: string) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.UPDATE_INVENTORIES, id],
    mutationFn: (data: Partial<IInventoriesStorage>) =>
      patchInventories(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useGetInventoriesById = (id: string) => {
  return useQuery({
    queryKey: [QUERY_KEY.INVENTORIES, id],
    queryFn: () => getInventoriesById(id),
    select: data => data.data,
    enabled: !!id,
  });
};

export const useDeleteInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.DELETE_INVENTORIES],
    mutationFn: (id: string) => deleteInventories(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useReviewInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REVIEW_INVENTORIES],
    mutationFn: (id: string) => reviewInventories(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useConfirmInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.APPROVE_INVENTORIES],
    mutationFn: ({
      id,
      data,
    }: {
      id: string;
      data: { assignSign: string; approvedSignName: string };
    }) => confirmInventories(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useRejectInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REJECT_INVENTORIES],
    mutationFn: ({ id, note }: { id: string; note: string }) =>
      rejectInventories(id, note),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useGetInventoriesAutoGeneratedCode = () => {
  return useQuery({
    queryKey: [QUERY_KEY.INVENTORIES_AUTO_CODE],
    queryFn: () => getInventoriesGeneratedCode(),
    select: data => data.data,
  });
};

export const useConfirmImportInventories = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.APPROVE_INVENTORIES],
    mutationFn: (id: string) => confirmImportInventories(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.INVENTORIES],
      });
    },
  });
};

export const useInventoriesStorageItems = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationKey: [MUTATION_KEY.INVENTORIES_STORAGES],
    mutationFn: getInventoriesStorageItems,
    onSuccess: data => {
      queryClient.setQueryData([MUTATION_KEY.INVENTORIES_STORAGES], data?.data);
    },
  });
};

export const useGetResultInventoriesStorageItems = () => {
  const queryClient = useQueryClient();

  interface IResult {
    itemId: string;
    totalQuantity: number;
  }

  return queryClient.getQueryData<IResult[]>([
    MUTATION_KEY.INVENTORIES_STORAGES,
  ]);
};

export const useGetInventoriesStorageItemsAllByWarehouse = (
  whId: string,
  filter: PaginationParams,
) => {
  return useQuery({
    queryKey: [QUERY_KEY.INVENTORIES_STORAGES, whId, filter],
    queryFn: () => getInventoriesStorageItemsAllByWarehouse(whId, filter),
    select: data => data.data,
    enabled: !!whId,
  });
};
