import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MUTATION_KEY, QUERY_KEY } from 'app/constants/query-key';
import paymentRequestService from 'app/services/payment-request.service';
import { PAYMENT_REQUEST_TYPE } from 'app/shared/model/enumerations/payment-request';
import { IIncomingInvoiceParams } from 'app/shared/model/incoming-invoice.model';
import {
  IPatchPaymentRequestDto,
  IPaymentRequestApproval,
  IPaymentRequestReject,
  IPostPaymentRequestDto,
} from 'app/shared/model/payment-request.model';
import { useState } from 'react';

const { PAYMENT_REQUEST, PAYMENT_REQUEST_DETAIL, PAYMENT_REQUEST_AUTO_CODE } =
  QUERY_KEY;

const {
  PATMENT_REQUEST_CREATE,
  PATMENT_REQUEST_UPDATE,
  PATMENT_REQUEST_DELETE,
  PATMENT_REQUEST_APPROVE,
  PATMENT_REQUEST_REJECT,
  PATMENT_REQUEST_EXPORT_EXCEL,
} = MUTATION_KEY;

const useGetPaymentRequests = (filter?: IIncomingInvoiceParams) => {
  return useQuery({
    queryKey: [PAYMENT_REQUEST, filter],
    queryFn: paymentRequestService.getPaymentRequests({ ...filter }),
    select: data => data?.data,
  });
};

const useGetPaymentRequestAutoGeneratedCode = (type: PAYMENT_REQUEST_TYPE) => {
  return useQuery({
    queryKey: [PAYMENT_REQUEST_AUTO_CODE, type],
    queryFn: () =>
      paymentRequestService.getPaymentRequestAutoGeneratedCode(type),
    select: data => data?.data,
    enabled: !!type,
  });
};

const useGetPaymentRequestById = (id: string) => {
  return useQuery({
    queryKey: [PAYMENT_REQUEST_DETAIL, id],
    queryFn: () => paymentRequestService.getPaymentRequestById(id),
    select: data => data?.data,
    enabled: !!id,
  });
};

const usePostPaymentRequest = (toggleSuccess?: () => void) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [PATMENT_REQUEST_CREATE],
    mutationFn: (data: IPostPaymentRequestDto) =>
      paymentRequestService.postPaymentRequest(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST] });
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST_DETAIL] });

      toggleSuccess && toggleSuccess();
    },
  });
};

const usePatchPaymentRequest = (id: string, toggleSuccess: () => void) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [PATMENT_REQUEST_UPDATE],
    mutationFn: (data: IPatchPaymentRequestDto) =>
      paymentRequestService.patchPaymentRequest(data, id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST] });
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST_DETAIL] });

      toggleSuccess();
    },
  });
};

const useDeletePaymentRequest = (
  toggle: () => void,
  toggleSuccess: () => void,
) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [PATMENT_REQUEST_DELETE],
    mutationFn: (id: string) => paymentRequestService.deletePaymentRequest(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST] });
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST_DETAIL] });

      toggle();
      toggleSuccess();
    },
  });
};

const useCancelPaymentRequest = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationKey: [PATMENT_REQUEST_UPDATE],
    mutationFn: (id: string) => paymentRequestService.cancelPaymentRequest(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST] });
    },
  });
};

const useSendApprovePaymentRequest = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationKey: [PATMENT_REQUEST_UPDATE],
    mutationFn: (id: string) =>
      paymentRequestService.sendApprovePaymentRequest(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [PAYMENT_REQUEST] });
    },
  });
};

const useGetUniformExportReportExcel = () => {
  const queryClient = useQueryClient();
  const [enabled, setEnabled] = useState(false);

  const query = useQuery({
    queryKey: [PATMENT_REQUEST_EXPORT_EXCEL],
    queryFn: () => paymentRequestService.getPaymentRequestReportsExcel(),
    enabled,
  });

  const trigger = () => {
    setEnabled(true);
  };

  if (query.isSuccess) {
    queryClient.resetQueries({ queryKey: [PATMENT_REQUEST_EXPORT_EXCEL] });
  }

  if ((query.isSuccess || query.isError) && enabled) {
    setEnabled(false);
  }

  return { trigger, ...query };
};

const useApproveRequestPayment = (
  id: string,
  toggle?: () => void,
  toggleSuccess?: () => void,
) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [PATMENT_REQUEST_APPROVE, id],
    mutationFn: (data: IPaymentRequestApproval) =>
      paymentRequestService.approvePaymentRequest(data, id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [PAYMENT_REQUEST],
      });
      toggle && toggle();
      toggleSuccess && toggleSuccess();
    },
  });
};

const useRejectRequestPayment = (
  id: string,
  toggle?: () => void,
  toggleSuccess?: () => void,
) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [PATMENT_REQUEST_REJECT, id],
    mutationFn: (data: IPaymentRequestReject) =>
      paymentRequestService.rejectPaymentRequest(data, id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [PAYMENT_REQUEST],
      });
      toggle && toggle();
      toggleSuccess && toggleSuccess();
    },
  });
};

export default {
  useGetPaymentRequests,
  useGetPaymentRequestById,
  usePostPaymentRequest,
  usePatchPaymentRequest,
  useDeletePaymentRequest,
  useGetPaymentRequestAutoGeneratedCode,
  useCancelPaymentRequest,
  useSendApprovePaymentRequest,
  useGetUniformExportReportExcel,
  useApproveRequestPayment,
  useRejectRequestPayment,
};
