import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MUTATION_KEY, QUERY_KEY } from 'app/constants/query-key';
import {
  confirmLiquidationSupplierContracts,
  confirmSupplierContracts,
  deleteSupplierContracts,
  getSupplierContracts,
  getSupplierContractsById,
  getSupplierContractsGeneratedCode,
  getSupplierContractsXlsx,
  patchSupplierContracts,
  postSupplierContracts,
  rejectLiquidationSupplierContracts,
  rejectSupplierContracts,
  reviewLiquidationSupplierContracts,
  reviewSupplierContracts,
  changeStatusSupplierContracts,
} from 'app/services/supplier-contract.service';
import {
  ISupplierContract,
  ISupplierContractFilterParams,
} from 'app/shared/model/supplier-contract.model';
import { useState } from 'react';

export const useGetSupplierContracts = (
  filter?: ISupplierContractFilterParams,
) => {
  return useQuery({
    queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS, filter],
    queryFn: () => getSupplierContracts(filter),
    select: data => data?.data,
    placeholderData: old => old,
  });
};

export const useSupplierContractsExportXlsxLazyQuery = (
  filter?: ISupplierContractFilterParams,
) => {
  const queryClient = useQueryClient();
  const [enabled, setEnabled] = useState(false);

  const query = useQuery({
    queryKey: [QUERY_KEY.SUPPLIER_CONTRACT_EXPORT, filter],
    queryFn: () => getSupplierContractsXlsx(filter),
    enabled,
  });

  const trigger = () => {
    setEnabled(true);
  };

  if (query.isSuccess) {
    queryClient.resetQueries({
      queryKey: [QUERY_KEY.SUPPLIER_CONTRACT_EXPORT],
    });
  }

  if ((query.isSuccess || query.isError) && enabled) {
    setEnabled(false);
  }

  return { trigger, ...query };
};

export const usePostSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.CREATE_SUPPLIER_CONTRACT],
    mutationFn: postSupplierContracts,
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const usePatchSupplierContracts = (id: string) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.UPDATE_SUPPLIER_CONTRACT, id],
    mutationFn: (data: Partial<ISupplierContract>) =>
      patchSupplierContracts(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useGetSupplierContractsById = (id: string) => {
  return useQuery({
    queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS, id],
    queryFn: () => getSupplierContractsById(id),
    select: data => data.data,
    enabled: !!id,
  });
};

export const useDeleteSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.DELETE_SUPPLIER_CONTRACT],
    mutationFn: (id: string) => deleteSupplierContracts(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useReviewSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REVIEW_SUPPLIER_CONTRACT],
    mutationFn: (id: string) => reviewSupplierContracts(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useConfirmSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.APPROVE_SUPPLIER_CONTRACT],
    mutationFn: ({
      id,
      data,
    }: {
      id: string;
      data: { assignSign: string; approvedSignName: string };
    }) => confirmSupplierContracts(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useRejectSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REJECT_SUPPLIER_CONTRACT],
    mutationFn: ({ id, note }: { id: string; note: string }) =>
      rejectSupplierContracts(id, note),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useGetSupplierContractsAutoGeneratedCode = () => {
  return useQuery({
    queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
    queryFn: () => getSupplierContractsGeneratedCode(),
    select: data => data.data,
  });
};

export const useReviewLiquidationSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REVIEW_SUPPLIER_CONTRACT],
    mutationFn: (id: string) => reviewLiquidationSupplierContracts(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};


export const useChangeStatusSupplierContracts = (id:string) => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationKey: [MUTATION_KEY.CHANGE_STATUS_SUPPLIER_CONTRACT],
    mutationFn: (status: string) => changeStatusSupplierContracts(id, status),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};


export const useConfirmLiquidationSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.APPROVE_SUPPLIER_CONTRACT],
    mutationFn: ({
      id,
      data,
    }: {
      id: string;
      data: { assignSign: string; approvedSignName: string };
    }) => confirmLiquidationSupplierContracts(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};

export const useRejectLiquidationSupplierContracts = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REJECT_SUPPLIER_CONTRACT],
    mutationFn: ({ id, note }: { id: string; note: string }) =>
      rejectLiquidationSupplierContracts(id, note),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.SUPPLIER_CONTRACTS],
      });
    },
  });
};
