import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MUTATION_KEY, QUERY_KEY } from 'app/constants/query-key';
import {
  confirmStocktaking,
  deleteStocktaking,
  getStocktaking,
  getStocktakingById,
  getStocktakingGeneratedCode,
  getStocktakingXlsx,
  patchStocktaking,
  postStocktaking,
  rejectStocktaking,
  reviewStocktaking,
} from 'app/services/stocktaking.service';
import {
  IStocktaking,
  IStocktakingFilterParams,
} from 'app/shared/model/stocktaking.model';
import { useState } from 'react';

export const useGetStocktaking = (filter?: IStocktakingFilterParams) => {
  return useQuery({
    queryKey: [QUERY_KEY.STOCKTAKING, filter],
    queryFn: () => getStocktaking(filter),
    select: data => data?.data,
  });
};

export const useStocktakingExportXlsxLazyQuery = (
  filter?: IStocktakingFilterParams,
) => {
  const queryClient = useQueryClient();
  const [enabled, setEnabled] = useState(false);

  const query = useQuery({
    queryKey: [QUERY_KEY.STOCKTAKING_EXPORT, filter],
    queryFn: () => getStocktakingXlsx(filter),
    enabled,
  });

  const trigger = () => {
    setEnabled(true);
  };

  if (query.isSuccess) {
    queryClient.resetQueries({
      queryKey: [QUERY_KEY.STOCKTAKING_EXPORT],
    });
  }

  if ((query.isSuccess || query.isError) && enabled) {
    setEnabled(false);
  }

  return { trigger, ...query };
};

export const usePostStocktaking = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.CREATE_SUPPLIER_CONTRACT],
    mutationFn: postStocktaking,
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const usePatchStocktaking = (id: string) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.UPDATE_SUPPLIER_CONTRACT, id],
    mutationFn: (data: Partial<IStocktaking>) => patchStocktaking(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const useGetStocktakingById = (id: string) => {
  return useQuery({
    queryKey: [QUERY_KEY.STOCKTAKING, id],
    queryFn: () => getStocktakingById(id),
    select: data => data.data,
    enabled: !!id,
  });
};

export const useDeleteStocktaking = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.DELETE_SUPPLIER_CONTRACT],
    mutationFn: (id: string) => deleteStocktaking(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const useReviewStocktaking = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REVIEW_SUPPLIER_CONTRACT],
    mutationFn: (id: string) => reviewStocktaking(id),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const useConfirmStocktaking = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.APPROVE_SUPPLIER_CONTRACT],
    mutationFn: ({
      id,
      data,
    }: {
      id: string;
      data: { assignSign: string; approvedSignName: string };
    }) => confirmStocktaking(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const useRejectStocktaking = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationKey: [MUTATION_KEY.REJECT_SUPPLIER_CONTRACT],
    mutationFn: ({ id, note }: { id: string; note: string }) =>
      rejectStocktaking(id, note),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.STOCKTAKING],
      });
    },
  });
};

export const useGetStocktakingAutoGeneratedCode = () => {
  return useQuery({
    queryKey: [QUERY_KEY.STOCKTAKING],
    queryFn: () => getStocktakingGeneratedCode(),
    select: data => data.data,
  });
};
