import { zodResolver } from '@hookform/resolvers/zod';
import CardV2 from 'app/components/CardV2/CardV2';
import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT } from 'app/constants/common';
import { PATH } from 'app/constants/path';
import useEmployee from 'app/hooks/use-employee';
import useIncomingInvoice from 'app/hooks/use-incoming-invoice';
import usePaymentRequest from 'app/hooks/use-payment-request';
import { useModalsRequestPayment } from 'app/hooks/use-request-payment';
import { FORM } from 'app/shared/model/enumerations/form.model';
import {
  PAYMENT_REQUEST_STATUS,
  PAYMENT_REQUEST_TYPE,
} from 'app/shared/model/enumerations/payment-request';
import {
  RequestPaymentSchema,
  requestPaymentSchema,
} from 'app/validation/request-payment.validation';
import dayjs from 'dayjs';
import { useEffect } from 'react';
import { FormProvider, SubmitHandler, useForm } from 'react-hook-form';
import { DateObject } from 'react-multi-date-picker';
import { useNavigate, useParams } from 'react-router';
import { ButtonGroupHeader } from '../components/ButtonGroupHeader';
import RequestPaymentApproveModals from './request-payment-approve-modals';
import RequestPaymentApproveSuccessModals from './request-payment-approve-success-modals';
import RequestPaymentCancelModals from './request-payment-cancel-modals';
import RequestPaymentCancelSuccessModals from './request-payment-cancel-success-modals';
import RequestPaymentCreateSuccessModals from './request-payment-create-success-modals';
import RequestPaymentForm from './request-payment-form';
import RequestPaymentUpdateSuccessModals from './request-payment-update-success-modal';
import AuthGuard from 'app/components/guards/auth-guard';

const {
  usePostPaymentRequest,
  usePatchPaymentRequest,
  useGetPaymentRequestAutoGeneratedCode,
  useGetPaymentRequestById,
} = usePaymentRequest;
const { useNextIncomingInvoiceNumber } = useIncomingInvoice;
const { useGetEmployeesQuery } = useEmployee;

function RequestPaymentCreateModals() {
  const navigate = useNavigate();
  const { id } = useParams();
  const account = useAppSelector(state => state.authentication.account);

  const [
    { openApprovalSign, toggleApprovalSign },
    { openApprovalSignSuccess, toggleApprovalSignSuccess },
    { openReject, toggleReject },
    { openRejectSuccess, toggleRejectSuccess },
    { openCancel, toggleCancel },
    { openCancelSuccess, toggleCancelSuccess },
    { openCreateSuccess, toggleCreateSuccess },
    { openUpdateSuccess, toggleUpdateSuccess },
  ] = useModalsRequestPayment();

  let defaultPaymentDetail = {
    new: true,
    invoiceId: '',
    incomingInvoice: {
      invoiceNo: '',
      invoiceDate: new Date().toISOString(),
      totalAmount: '0',
      note: '',
    },
  };

  const methods = useForm<RequestPaymentSchema>({
    defaultValues: {
      status: PAYMENT_REQUEST_STATUS.NEW,
      createdDate: new DateObject(),
      paymentDate: new DateObject(),
      attachments: [],
      paymentDetails: [{ ...defaultPaymentDetail }],
      requestApprovals: [],
      createdByName: `${account?.lastName} ${account?.firstName}`,
    },
    resolver: zodResolver(requestPaymentSchema),
  });

  const { handleSubmit, setValue, reset, watch, formState } = methods;

  const statusWatch = watch('status');
  const createdByWatch = watch('createdBy');
  const paymentDetailsWatch = watch('paymentDetails');

  const { mutateAsync: create } = usePostPaymentRequest(toggleCreateSuccess);
  const { mutateAsync: update } = usePatchPaymentRequest(
    id,
    toggleUpdateSuccess,
  );
  const { data: employeeProfiles } = useGetEmployeesQuery();

  const { data: detail } = useGetPaymentRequestById(id);
  const { data: nextCode } = useGetPaymentRequestAutoGeneratedCode(
    PAYMENT_REQUEST_TYPE.PAYMENT,
  );
  const { data: nextInvoiceCode } = useNextIncomingInvoiceNumber();

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode)
        setValue('code', `TT${suffix}/${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  const onSubmit: SubmitHandler<RequestPaymentSchema> = values => {
    if (paymentDetailsWatch?.length !== 0) {
      const totalAmount = values.paymentDetails
        ?.filter(x => x.incomingInvoice?.invoiceNo)
        .reduce(
          (acc, obj) => acc + (Number(obj?.incomingInvoice?.totalAmount) ?? 0),
          0,
        );
      if (!id) {
        create({
          code: undefined,
          order: undefined,
          type: PAYMENT_REQUEST_TYPE.PAYMENT,
          attachments: values.attachments.map(x => ({
            fileId: x.fileId,
            fileName: x.fileName,
            createdAt: new Date(x.createdAt),
          })),
          totalAmount: totalAmount,
          paidAmount: 0,
          remainingAmount: 0,
          paymentDate: values.paymentDate.toDate(),
          note: values.note,
          content: values?.content,
          status: PAYMENT_REQUEST_STATUS.NEW,
          supplierId: values.supplierId,
          paymentVoucher: undefined, // Phiếu chi
          paymentVoucherAmount: 0, // Tổng tiền chi
          requestApprovals: values.requestApprovals
            ?.filter(x => x.employeeId)
            ?.map(x => ({
              index: x.index,
              employeeId: x.employeeId,
            })),
          employeeId: values?.employeeId,
          paymentDetails: values.paymentDetails
            ?.filter(
              x =>
                x.incomingInvoice?.totalAmount !== '' &&
                x.incomingInvoice?.totalAmount !== '0',
            )
            .map(x => ({
              invoiceId: x.invoiceId,
              incomingInvoice: {
                invoiceNo: x.incomingInvoice?.invoiceNo,
                invoiceDate: new Date(),
                content: x.incomingInvoice?.content,
                totalAmount: Number(x.incomingInvoice?.totalAmount),
                series: x.incomingInvoice?.series,
                note: x.incomingInvoice?.note,
                documentId: x.incomingInvoice?.documentId,
                grandTotal: Number(x.incomingInvoice?.totalAmount),
              },
            })),
        }).then(() => reset());
        return;
      } else {
        update({
          id: id ?? '',
          type: PAYMENT_REQUEST_TYPE.PAYMENT,
          attachments: values.attachments.map(x => ({
            fileId: x.fileId,
            fileName: x.fileName,
            createdAt: new Date(x.createdAt),
          })),
          totalAmount: totalAmount,
          paidAmount: 0,
          remainingAmount: 0,
          paymentDate: values.paymentDate.toDate(),
          note: values.note,
          content: values?.content,
          status: PAYMENT_REQUEST_STATUS.NEW,
          supplierId: values.supplierId,
          paymentVoucher: undefined, // Phiếu chi
          paymentVoucherAmount: 0, // Tổng tiền chi
          requestApprovals: values.requestApprovals
            ?.filter(x => x.employeeId)
            ?.map(x => ({
              id: x.id,
              index: x.index,
              employeeId: x.employeeId,
            })),
          employeeId: values?.employeeId,
          paymentDetails: values.paymentDetails
            ?.filter(
              x =>
                x.incomingInvoice?.invoiceNo &&
                x.incomingInvoice?.totalAmount !== '0' &&
                x.incomingInvoice?.totalAmount !== '',
            )
            ?.map(x => ({
              id: x.id,
              invoiceId: x.invoiceId,
              incomingInvoice: {
                invoiceNo: x.incomingInvoice?.invoiceNo,
                invoiceDate: new Date(),
                content: x.incomingInvoice?.content,
                totalAmount: Number(x.incomingInvoice?.totalAmount),
                series: x.incomingInvoice?.series,
                note: x.incomingInvoice?.note,
                documentId: x.incomingInvoice?.documentId,
                grandTotal: Number(x.incomingInvoice?.totalAmount),
              },
            })),
        });
      }
    }
  };

  const loadDefaultPaymentDetail = () => {
    if (nextInvoiceCode?.nextAndIncrement) {
      if (id) {
        const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);

        defaultPaymentDetail = {
          ...defaultPaymentDetail,
          incomingInvoice: {
            ...defaultPaymentDetail.incomingInvoice,
            invoiceNo: `HDNK${suffix}/${nextInvoiceCode?.currentSequence}`,
          },
        };
        if (detail) {
          const existPaymentDetail = detail?.paymentDetails?.map(x => ({
            ...x,
            id: x.id,
            incomingInvoice: {
              ...x.incomingInvoice,
              totalAmount: (x?.incomingInvoice?.grandTotal ?? 0)?.toString(),
              // totalAmount: (x?.incomingInvoice?.totalAmount ?? 0)?.toString(),
              invoiceDate: new Date(
                x.incomingInvoice.invoiceDate,
              )?.toISOString(),
            },
          }));
          setValue('paymentDetails', [
            ...existPaymentDetail,
            defaultPaymentDetail,
          ]);
        }
      } else {
        const defaultItem = paymentDetailsWatch.findIndex(
          x =>
            x.incomingInvoice.totalAmount === '0' &&
            x.incomingInvoice.invoiceNo === '',
        );
        if (defaultItem > -1) {
          const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
          setValue(
            `paymentDetails.${defaultItem}.incomingInvoice.invoiceNo`,
            `HDNK${suffix}/${nextInvoiceCode?.nextAndIncrement}`,
          );
        }
      }
    }
  };

  useEffect(() => {
    if (detail) {
      setValue('code', detail?.code);
      setValue('paymentDate', new DateObject(detail?.paymentDate));
      setValue('supplierId', detail?.supplierId);
      setValue('supplierCodeName', `${detail?.suppliers?.name}`);
      setValue('content', detail?.content);
      setValue('status', detail?.status);

      setValue('employeeId', detail?.employeeId);

      const empSelected = employeeProfiles?.data?.find(
        x => x.id === detail?.employeeId,
      );
      const empWorkspace = empSelected
        ? `${empSelected.workspace.normalizedName} - ${empSelected.workspace?.name}`
        : '';
      setValue('workspaceName', empWorkspace);

      setValue('requestApprovals', detail?.requestApprovals);

      const existPaymentDetail = detail?.paymentDetails?.map(x => ({
        ...x,
        id: x.id,
        incomingInvoice: {
          ...x.incomingInvoice,
          totalAmount: (x?.incomingInvoice?.grandTotal ?? 0)?.toString(),
          // totalAmount: (x?.incomingInvoice?.totalAmount ?? 0)?.toString(),
          invoiceDate: new Date(x.incomingInvoice.invoiceDate)?.toISOString(),
        },
      }));
      setValue('paymentDetails', [...existPaymentDetail, defaultPaymentDetail]);

      const existAttachments = detail?.attachments?.map(x => ({
        ...x,
        createdAt: new Date(x.createdAt),
      }));
      setValue('attachments', existAttachments);

      setValue('createdDate', new DateObject(detail?.createdDate));

      const createdByName = [
        detail?.createdByEmployee?.employeeCode,
        detail?.createdByEmployee?.fullName,
      ].join(' - ');
      setValue('createdByName', createdByName);
      setValue('createdBy', detail?.createdBy);
    }

    loadDefaultPaymentDetail();
  }, [detail, employeeProfiles, nextInvoiceCode]);

  return (
    <>
      <FormProvider {...methods}>
        <Form id={FORM.REQUEST_PAYMENT} onSubmit={handleSubmit(onSubmit)}>
          <CardV2
            header={
              <Flex justify="space-between" align="center">
                <Typography level={4}>DNTT</Typography>
                <AuthGuard permissionKey={!!id ? 'REQUEST_PAYMENT.EDIT' : 'REQUEST_PAYMENT.CREATE'}>
                  <ButtonGroupHeader
                    status={statusWatch}
                    createdBy={createdByWatch}
                    toggleCancel={toggleCancel}
                    toggleSendApprove={toggleApprovalSign}
                    disableSendApproved={detail?.requestApprovals?.length === 0}
                    type={PAYMENT_REQUEST_TYPE.PAYMENT}
                  />
                </AuthGuard>
              </Flex>
            }
          >
            <RequestPaymentForm type="create" />
          </CardV2>
        </Form>
      </FormProvider>

      <RequestPaymentCreateSuccessModals
        isOpen={openCreateSuccess}
        toggle={() => {
          toggleCreateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RequestPaymentUpdateSuccessModals
        isOpen={openUpdateSuccess}
        toggle={() => {
          toggleUpdateSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RequestPaymentCancelModals
        isOpen={openCancel}
        toggle={toggleCancel}
        toggleSuccess={toggleCancelSuccess}
        selectedRecord={id}
      />

      <RequestPaymentCancelSuccessModals
        isOpen={openCancelSuccess}
        toggle={() => {
          toggleCancelSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />

      <RequestPaymentApproveModals
        isOpen={openApprovalSign}
        toggle={toggleApprovalSign}
        toggleSuccess={toggleApprovalSignSuccess}
        selectedRecord={id}
      />

      <RequestPaymentApproveSuccessModals
        isOpen={openApprovalSignSuccess}
        toggle={() => {
          toggleApprovalSignSuccess();
          navigate(PATH.REQUEST_PAYMENT);
        }}
      />
    </>
  );
}

export default RequestPaymentCreateModals;
