package com.masi.utility.service;

import com.masi.utility.domain.enumeration.CronJobStatus;
import com.masi.utility.repository.CronJobRepository;
import com.masi.utility.service.dto.CronJobDTO;
import com.masi.utility.service.dto.WorkScheduleQuery;
import com.masi.utility.service.mapper.CronJobMapper;
import com.masi.utility.service.web.client.EmployeeCronjobClient;
import com.masi.utility.service.web.client.SaleWebClient;

import lombok.AllArgsConstructor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Pageable;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.web.PortResolverImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Service Implementation for managing {@link com.masi.utility.domain.CronJob}.
 */
@Service
@AllArgsConstructor
public class CronJobService {

    private static final Logger log = LoggerFactory.getLogger(CronJobService.class);

    private final CronJobRepository cronJobRepository;

    private final CronJobMapper cronJobMapper;
    private final EmployeeCronjobClient employeeCronjobClient;
    private final SaleWebClient saleWebClient;
    private static final ZoneId UTC = ZoneId.of("UTC");
    private final StandardWorkScheduleConfigService standardWorkScheduleConfigService;

//    @Scheduled(fixedRate = 1000, timeUnit = TimeUnit.MINUTES)
//    public void test() {
//        LocalDate date = LocalDate.now().plusDays(3);
//        var dayOfWeek = date.getDayOfWeek().getValue();
//        List<String> company = List.of("KIM_LONG", "MMS");
//        Flux.fromIterable(company)
//            .flatMap(c -> {
//                log.info("Auto create shift for company1 {}", c);
//                WorkScheduleQuery query = new WorkScheduleQuery();
//                query.setCompany(c);
//                query.setWorkspaceType("OFFICE");
//                return standardWorkScheduleConfigService.findByQuery(query).flatMap(
//                    e -> {
//                        var sh = e.stream().filter(
//                            f -> f.getDayOfWeek() == dayOfWeek
//                        ).findFirst().orElse(null);
//                        if (sh == null) {
//                            return Mono.empty();
//                        }
//                        log.info("Auto create shift for company1 {} at {} with dayofweek {}", c, date, dayOfWeek);
//                        return employeeCronjobClient.autoGenerateDailyShiftsEmployee(c, date, List.of(sh.getId()));
//                    }
//                );
//            }).collectList().subscribe();
//
//    }

    // chạy ỗi mong 1 phút

    /**
     * Save a cronJob.
     *
     * @param cronJobDTO the entity to save.
     * @return the persisted entity.
     */
    public Mono<CronJobDTO> save(CronJobDTO cronJobDTO) {
        log.debug("Request to save CronJob : {}", cronJobDTO);
        return cronJobRepository.save(cronJobMapper.toEntity(cronJobDTO)).map(cronJobMapper::toDto);
    }


    public Mono<CronJobDTO> partialUpdate(CronJobDTO cronJobDTO) {
        log.debug("Request to partially update CronJob : {}", cronJobDTO);

        return cronJobRepository
            .findById(cronJobDTO.getId())
            .map(existingCronJob -> {
                cronJobDTO.applyChanges(existingCronJob);
                existingCronJob.calculateNextRun();
                log.info("Partial update CronJob : {}", existingCronJob);
                return existingCronJob.setIsPersisted();
            })
            .flatMap(cronJobRepository::save)
            .map(cronJobMapper::toDto);
    }

    /**
     * Get all the cronJobs.
     *
     * @param pageable the pagination information.
     * @return the list of entities.
     */
    @Transactional(readOnly = true)
    public Flux<CronJobDTO> findAll(Pageable pageable) {
        log.debug("Request to get all CronJobs");
        return cronJobRepository.findAllBy(pageable).map(e -> cronJobMapper.toDto(e).toClient());
    }

    /**
     * Returns the number of cronJobs available.
     *
     * @return the number of entities in the database.
     */
    public Mono<Long> countAll() {
        return cronJobRepository.count();
    }

    /**
     * Get one cronJob by id.
     *
     * @param id the id of the entity.
     * @return the entity.
     */
    @Transactional(readOnly = true)
    public Mono<CronJobDTO> findOne(Long id) {
        log.debug("Request to get CronJob : {}", id);
        return cronJobRepository.findById(id).map(e -> cronJobMapper.toDto(e).toClient());
    }


    public Mono<Void> delete(Long id) {
        log.debug("Request to delete CronJob : {}", id);
        return cronJobRepository.findById(id)
            .flatMap(cronJob -> {
                cronJob.setIsPersisted();
                cronJob.setUpdatedAt(ZonedDateTime.now());
                cronJob.setEnabled(!cronJob.getEnabled());
                return cronJobRepository.save(cronJob.setIsPersisted()).then();
            });
    }

    @Scheduled(fixedRate = 7200, timeUnit = TimeUnit.SECONDS)
    public void scheduleFixedRateTask() {
        var zdt = ZonedDateTime.now();
        log.info("Scanning for cron jobs at {}", zdt);

        cronJobRepository.findNextCronJobs(zdt).flatMap(cronJob -> {
            cronJob.setZoneId(UTC.toString());
            log.info("Running cron job {}", cronJob.getName());
            if (cronJob.getNextRun().isBefore(ZonedDateTime.of(2022, 1, 1, 0, 0, 0, 0, ZoneId.of("UTC")))) {
                cronJob.setLastRun(ZonedDateTime.now().withZoneSameLocal(UTC));
                cronJob.calculateNextRun();
                cronJob.setIsPersisted();
                return cronJobRepository.save(cronJob);
            }
            switch (cronJob.getAction()) {
                case "SALE_CLEAN_OLD_DELETED_CONTRACT":
                    cronJob.setLastRun(ZonedDateTime.now());
                    log.info("Running cron job at {}", zdt);
                    //todo: run customer birthday
                    // call webclient to sale service:
                    //saleWebClient.cleanOldDeletedContract().subscribe();

                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    return saleWebClient.cleanOldDeletedContract().then(cronJobRepository.save(cronJob));
                case "AUTO_CREATE_SHIFT":
                    cronJob.setLastRun(ZonedDateTime.now());
                    log.info("Tạo ca làm việc tự động");
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    LocalDate date = LocalDate.now().plusDays(3);
                    var dayOfWeek = date.getDayOfWeek().getValue();
                    List<String> company = List.of("KIM_LONG", "MMS");
                    return Flux.fromIterable(company)
                            .flatMap(c -> {
                                log.info("Auto create shift for company {}", c);
                                WorkScheduleQuery query = new WorkScheduleQuery();
                                query.setCompany(c);
                                query.setWorkspaceType("OFFICE");
                                return standardWorkScheduleConfigService.findByQuery(query).map(
                                        e -> {
                                            var sh = e.stream().filter(
                                                    f -> f.getDayOfWeek() == dayOfWeek
                                            ).findFirst().orElse(null);
                                            if (sh == null) {
                                                return Mono.empty();
                                            }
                                            log.info("Auto create shift for company {} at {} with dayofweek {}", c, date, dayOfWeek);
                                            return employeeCronjobClient.autoGenerateDailyShiftsEmployee(c, date, List.of(sh.getId()));
                                        }
                                );
                            }).collectList().then(cronJobRepository.save(cronJob));
                case "SALE_CUSTOMER_BIRTHDAY":
                    // run customer birthday
                    cronJob.setLastRun(ZonedDateTime.now());
                    log.info("Running cron job at {}", zdt);
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    var send = saleWebClient.sendCustomerBirthdayNotify();
                    return send.then(cronJobRepository.save(cronJob));
                case "CHECK_DATE_TIME_KEEPING_VIOLATION":
                    cronJob.setLastRun(ZonedDateTime.now());
                    Mono<Void> voidMono = employeeCronjobClient.autoCreateTimeKeepingViolation().doAfterTerminate(() -> log.info("Time keeping violation cron job completed"));
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    return voidMono.then(cronJobRepository.save(cronJob));
                case "LOCK_WEEK_TIME_KEEPING":
                    cronJob.setLastRun(ZonedDateTime.now());
                    Mono<Void> voidMono1 = employeeCronjobClient.autoLockTimeKeeping().doAfterTerminate(() -> log.info("Time keeping cron job completed"));
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    return voidMono1.then(cronJobRepository.save(cronJob));
                case "CLEANUP_OLD_DELETED_CONTRACTS":
                    cronJob.setLastRun(ZonedDateTime.now());
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    return employeeCronjobClient.autoCleanupOldDeletedContracts().then(cronJobRepository.save(cronJob));
                case "UPDATE_DATA_TIMEKEEPING":
                    ZonedDateTime timeStart = cronJob.getLastRun();
                    ZonedDateTime timeEnd = ZonedDateTime.now();
                    cronJob.setLastRun(ZonedDateTime.now());
                    cronJob.calculateNextRun();
                    cronJob.setStatus(CronJobStatus.COMPLETED);
                    cronJob.setIsPersisted();
                    log.info("Running end cron job at {}", ZonedDateTime.now());
                    return employeeCronjobClient.updateDataTimeKeeping(cronJob.getUrlDb(), cronJob.getUserDb(), cronJob.getPwDb(), timeStart, timeEnd)
                            .then(Mono.fromRunnable(() -> log.info("Running end cron job at {}", ZonedDateTime.now())))
                            .then(cronJobRepository.save(cronJob));
                default:
                    log.error("Unknown cron job action {}", cronJob.getAction());
            }
            return Mono.empty();
        }).collectList().subscribe();
        log.info("Cron job finished at {}", ZonedDateTime.now());
    }

}
