import Flex from 'app/components/flex/flex';
import Form from 'app/components/form/form';
import FormSelect from 'app/components/form/form-select';
import FormDatePickerV2 from 'app/components/formV2/form-date/form-date-picker';
import FormInputV2 from 'app/components/formV2/form-input/form-input';
import { Typography } from 'app/components/typography/typography';
import { useAppSelector } from 'app/config/store';
import { DATE_FORMAT, DEFAULT_PAGE_SIZE_NAX } from 'app/constants/common';
import useEmployee from 'app/hooks/use-employee';
import {
  useGetStocktakingAutoGeneratedCode,
  usePatchStocktaking,
  usePostStocktaking,
} from 'app/hooks/use-stocktaking';
import useWarehouse from 'app/hooks/use-warehouse';
import { FORM } from 'app/shared/model/enumerations/form.model';
import { STOCKTAKING_STATUS } from 'app/shared/model/stocktaking.model';
import { StocktakingSchema } from 'app/validation/stocktaking.validation';
import dayjs from 'dayjs';
import { useContext, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import { useParams } from 'react-router';
import { Col, Row } from 'reactstrap';
import { StocktakingContext } from '../stocktaking-provider';
import StocktakingAttachments from './StocktakingAttachments';
import { StocktakingItemsTable } from './StocktakingItemsTable';
import StocktakingPersonSign from './StocktakingPersonSign';

const { useGetWarehouses } = useWarehouse;
const { useGetEmployeesQuery } = useEmployee;

interface IStocktakingFormProps {
  type: 'create' | 'update';
}

const StocktakingForm = ({ type }: IStocktakingFormProps) => {
  const { id } = useParams();

  const account = useAppSelector(state => state.authentication.account);

  const { toggleCreateSuccess, toggleUpdateSuccess } =
    useContext(StocktakingContext);

  const { data: warehouses } = useGetWarehouses({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const { mutate: createStocktaking } = usePostStocktaking();
  const { mutate: updateStocktaking } = usePatchStocktaking(id);

  const { data: nextCode } = useGetStocktakingAutoGeneratedCode();
  const { data: employees } = useGetEmployeesQuery({
    size: DEFAULT_PAGE_SIZE_NAX,
  });

  const { control, handleSubmit, setValue, watch, reset, formState } =
    useFormContext<StocktakingSchema>();

  const inventoryPersonWatch = watch('inventoryPerson');

  useEffect(() => {
    if (!id) {
      const suffix = dayjs(new Date()).format(DATE_FORMAT.MONTH_YEAR);
      if (nextCode) setValue('code', `${nextCode?.nextAndIncrement}`);
    }
  }, [nextCode]);

  useEffect(() => {
    if (employees?.data?.length && account?.id && !id) {
      const selected = employees?.data?.find(x => `${x.id}` === account?.id);
      if (selected)
        setValue(
          'createdByName',
          `${selected?.code} - ${selected?.lastName} ${selected?.firstName}`,
        );
    }
  }, [employees]);

  const onSubmit = (values: StocktakingSchema) => {
    const employees = [];

    values.inventoryPerson.map((detail, idx) => {
      employees[`approver${idx + 1}`] = detail?.id;
    });

    const submitValues = {
      ...values,
      ...employees,
      checkDate: values?.checkDate.toDate(),

      attachment: values.attachments?.map(f => ({
        fileId: f.fileId,
        fileName: f.fileName,
        createdAt: f.createdAt,
      })),

      requestApprovals: values.requestApprovals
        ?.filter(x => x.employeeId)
        ?.map(x => ({
          index: x.index,
          employeeId: x.employeeId,
        })),
      status: STOCKTAKING_STATUS.NEW,
      createdAt: undefined,

      listInventoriesCheckDetail: values?.itemInventories?.map(x => ({
        itemId: x?.itemId,
        systemQuantity: Number(x?.totalQty ?? 0),
        actualQuantity: Number(x?.totalQtyActual ?? 0),
        note: x?.note,
      })),

      amountOfDifference: values?.itemInventories?.reduce(
        (acc, obj) =>
          acc + (Number(obj?.totalQty ?? 0) - Number(obj?.totalQtyActual ?? 0)),
        0,
      ),
    };

    delete submitValues?.inventoryPerson;
    delete submitValues?.itemInventories;

    if (type === 'update') {
      updateStocktaking(submitValues, {
        onSuccess: () => {
          toggleUpdateSuccess();
          reset();
        },
      });
      return;
    }

    createStocktaking(submitValues, {
      onSuccess: () => {
        toggleCreateSuccess();
        reset();
      },
    });
  };

  const disabled =
    watch('status') === (STOCKTAKING_STATUS.WAITING_APPROVED as string) ||
    watch('status') === (STOCKTAKING_STATUS.CANCELLED as string) ||
    watch('status') === (STOCKTAKING_STATUS.APPROVED as string) ||
    watch('status') === (STOCKTAKING_STATUS.COMPLETED as string);

  const errorMsg = (idx: number) => {
    if (idx === 0) {
      const message = formState.errors?.inventoryPerson?.message;
      const root = formState.errors?.inventoryPerson?.root;
      if (message || root) return message || root?.message;
    }
    return null;
  };

  return (
    <Form id={FORM.STOCKTAKING} onSubmit={handleSubmit(onSubmit)}>
      <Flex direction="column" gap={20}>
        <Typography level={5}>Thông tin chung</Typography>
        <Row>
          <Col md={4}>
            <FormInputV2
              control={control}
              name="code"
              label="Mã phiếu"
              disabled
            />
          </Col>

          <Col md={4}>
            <FormDatePickerV2
              control={control}
              formState={formState}
              name="checkDate"
              label="Ngày kiểm"
              placeholder="Chọn ngày"
              setValue={setValue}
              disabled={disabled}
            />
          </Col>

          <Col md={4}>
            <FormSelect
              control={control}
              name="warehouseId"
              label="Kho hàng"
              placeholder="Vui lòng chọn kho hàng"
              disabled={disabled}
              isClearable={false}
              options={
                warehouses?.data?.map(w => ({
                  label: `${w.code}  ${w.name}`,
                  value: w.id,
                })) || []
              }
            />
          </Col>

          <Col md={12}>
            <FormInputV2
              control={control}
              name="note"
              label="Ghi chú"
              disabled={disabled}
            />
          </Col>
        </Row>

        <Typography level={5}>Người kiểm</Typography>
        <Row>
          <Col md={4}>
            <Flex direction="column">
              {new Array(3).fill(0).map((_x, idx) => (
                <Row key={idx}>
                  <Col md={4} style={{ marginTop: '6px' }}>
                    Thành viên {idx + 1}
                  </Col>
                  <Col md={8}>
                    <FormSelect
                      control={control}
                      name={`inventoryPerson.${idx}.id`}
                      options={employees?.data?.map(x => ({
                        value: `${x?.id}`,
                        label: `${x.code} - ${x?.employeeProfile?.fullName}`,
                      }))}
                      onChanges={e => {
                        const selected = employees?.data?.find(x => x.id === e);
                        if (selected)
                          setValue(
                            `inventoryPerson.${idx}.position`,
                            selected?.workspace?.name,
                          );
                      }}
                      isClearable={false}
                      disabled={disabled}
                      isOptionDisabled={e =>
                        inventoryPersonWatch?.map(x => x.id)?.includes(e?.value)
                      }
                      errorMsg={errorMsg(idx)}
                    />
                  </Col>
                </Row>
              ))}
            </Flex>
          </Col>
          <Col md={4}>
            <Flex direction="column">
              {new Array(3).fill(0).map((_x, idx) => (
                <Row key={idx}>
                  <Col md={4} style={{ marginTop: '6px', textAlign: 'right' }}>
                    Chức vụ
                  </Col>
                  <Col md={8}>
                    <FormInputV2
                      control={control}
                      name={`inventoryPerson.${idx}.position`}
                      disabled
                    />
                  </Col>
                </Row>
              ))}
            </Flex>
          </Col>
        </Row>

        <StocktakingItemsTable />

        <Row>
          <Col md={6}>
            <StocktakingPersonSign />
          </Col>
          <Col md={6}>
            <StocktakingAttachments />
          </Col>
        </Row>
      </Flex>
    </Form>
  );
};

export default StocktakingForm;
